# Avance Fase 3 — Semana 2 · Sumativa 2

## Núcleo algorítmico, eficiencia e implementación orientada a objetos

**Proyecto:** Uso de redes sociales y salud mental percibida en adolescentes (YRBS 2023, CDC)
**Grupo 8 · MCDI500 Programación para la Ciencia de Datos** — Matías Manriquez Ortiz, Daniel Pérez Ramirez, Abigail Robles Chávez, Roberto Sánchez Saldivia
**Docente:** Dr. Omar Salinas Silva · **Repositorio:** https://github.com/MatiasManriquezO/proyecto-grupo8-mcdi500

> **Este es el notebook central de la Sumativa 2.** El cuaderno de la Formativa 3 se conserva
> como registro histórico en `F3/notebooks/formativa3/` y no forma parte de esta entrega.

---

En la Fase 2 construimos un pipeline que funciona: lee el archivo original del CDC,
selecciona 11 de 117 columnas, conserva los faltantes con una bandera, declara el tipo de
cada código y crea columnas 0/1. En la Formativa 3 escribimos los scripts del núcleo
algorítmico (tabla de contingencia, búsqueda, recursión) y medimos su costo. Este cuaderno
integra ambas cosas y las organiza como un **sistema de clases** que vive en `F3/src/`:
cada paso pasa a ser una pieza que se puede probar, reemplazar y reutilizar.

No hay datos nuevos ni pipeline nuevo. **Lo que cambia es la arquitectura del código.** La
prueba de que la reorganización no rompió nada está en la sección 16: el pipeline de clases
produce un archivo **idéntico, carácter por carácter**, al de la Fase 2.

> **Este cuaderno no define ninguna clase.** Todas viven en `F3/src/`, en los archivos que proyectó
> la Tabla 8 de la Formativa 3 (`carga.py`, `transformadores.py`, `pipeline.py`, `fabrica.py`,
> `observadores.py`, `medicion.py`), y el cuaderno las importa; cuando conviene leerlas, las muestra
> con `inspect.getsource`. La sección 17 lo comprueba contra esa tabla.
>
> **Sobre los ejemplos de las secciones 2 a 10.** Para explicar cada concepto se usan clases
> pequeñas (imputar, escalar, codificar). Son **didácticas**: en el proyecto no se imputa ni se
> escala (bitácora 2.4 y 2.5). Están separadas del código del proyecto dentro de `F3/src/`
> (`CLASES_DIDACTICAS` en `transformadores.py` y el módulo `didacticos.py`).

### Recorrido

| Parte | Contenido | Dónde vive el código |
|---|---|---|
| 0 | Configuración, carga y perfil del conjunto | configuración en el cuaderno; `F3/src/carga.py` |
| 1–3 | De funciones a objetos; `Preprocesador`; encapsulamiento | `F3/src/didacticos.py` |
| 4–5 | Herencia, polimorfismo y `Pipeline` | `F3/src/transformadores.py`, `F3/src/pipeline.py` |
| 6 | Cohesión y acoplamiento | `F3/src/didacticos.py` + estructura de `F3/src/` |
| 7 | Validación de las clases base | cuaderno (pruebas) |
| 8 | Recursividad: criterio del proyecto | `F3/src/recursion.py` |
| 9 | Eficiencia: medir tiempo y memoria | `F3/src/medicion.py` |
| 10 | Patrones de diseño (Strategy, Factory, Observer) | `estrategias.py`, `fabrica.py`, `observadores.py` |
| **11** | **El pipeline de la Fase 2 en clases** | `transformadores.py`, `estrategias.py`, `fabrica.py` |
| **12** | **Eficiencia sobre un paso real: conteo de faltantes** | `transformadores.py` |
| **13** | **Integración del avance formativo: contingencia y búsqueda** | `contingencia.py`, `busqueda.py`, `analisis.py` |
| **14** | **Recursión con memoización: prevalencia por segmentos** | `segmentacion.py` |
| **15** | **Validación del pipeline real y del núcleo** | cuaderno (pruebas) |
| **16** | **Strategy y verificación contra la Fase 2** | `estrategias.py` |
| 17 | Arquitectura generada desde el código, Tabla 8 ejecutada y registro | `F3/resultados/` |

**Cómo ejecutarlo.** Abrir el cuaderno desde cualquier carpeta del repositorio y usar
*Restart Kernel and Run All Cells*. La primera celda localiza la raíz del proyecto; los datos se
leen desde `F1/data/raw/` (archivo original) y `F2/data/processed/` (salida de la Fase 2).

---
## Configuración

**Esta es la única celda que hay que editar.** Todo lo que sigue se construye a partir
de ella.

In [1]:
# =====================================================================
# CONFIGURACIÓN DEL PROYECTO
# Todas las rutas y nombres de columna se declaran acá, una sola vez.
# =====================================================================
from pathlib import Path


def encontrar_raiz(marcador="requirements.txt"):
    """Sube desde la carpeta actual hasta encontrar la raíz del repositorio.

    Así el cuaderno funciona se abra desde F3/notebooks/ o desde la raíz.
    """
    for carpeta in [Path.cwd(), *Path.cwd().parents]:
        if (carpeta / marcador).exists() and (carpeta / "F3").is_dir():
            return carpeta
    raise FileNotFoundError("No se encontró la raíz del repositorio (requirements.txt y F3/).")


RAIZ = encontrar_raiz()
RUTA_DATOS = RAIZ / "F2" / "data" / "processed" / "yrbs2023_seleccion_procesada.csv"  # salida de F2
RUTA_ORIGINAL = RAIZ / "F1" / "data" / "raw" / "XXH2023_YRBSS_data.csv"              # archivo del CDC
RUTA_SRC_F2 = RAIZ / "src"                    # módulo de F1-F2: procesamiento.py (constantes, carga)
RUTA_SRC_F3 = RAIZ / "F3" / "src"             # núcleo algorítmico de F3 (clases y scripts)
CARPETA_RESULTADOS = RAIZ / "F3" / "resultados"

COLUMNA_OBJETIVO = "salud_mental_cod"          # desenlace: salud mental percibida (q84)
COLUMNA_ID = "id_registro"                     # identificador: no describe, solo identifica

COLUMNAS_CONTINUAS = ["redes_sociales_cod", "sueno_cod", "actividad_fisica_cod", "edad_cod"]
COLUMNAS_NOMINALES = ["raceeth_cod", "sexo_cod"]

SEMILLA = 42
PROPORCION_PRUEBA = 0.2

# Columnas usadas en los ejemplos didácticos (secciones 2 a 10)
COLUMNA_IMPUTAR = "actividad_fisica_cod"   # con faltantes (6,1 %): ejemplos de imputación
COLUMNA_ESCALAR = "edad_cod"               # ejemplos de escalamiento
COLUMNA_GRUPO = "sexo_cod"                 # imputación por grupo (Strategy didáctico)
COLUMNA_CLASIFICAR = "sueno_cod"           # comparación bucle vs. vectorizado

# Núcleo analítico (sección 14): jerarquía de segmentos y tamaño mínimo
JERARQUIA_SEGMENTOS = ["redes_sociales_cod", "sexo_cod", "edad_cod"]
N_MINIMO_SEGMENTO = 30
# =====================================================================

COLUMNAS_ESPERADAS = ([COLUMNA_ID, COLUMNA_OBJETIVO] + COLUMNAS_CONTINUAS
                      + COLUMNAS_NOMINALES)

print("Raíz del proyecto   :", RAIZ.name)
print("Archivo de la Fase 2:", RUTA_DATOS.relative_to(RAIZ).as_posix())
print("Archivo original    :", RUTA_ORIGINAL.relative_to(RAIZ).as_posix())
print("Variable objetivo   :", COLUMNA_OBJETIVO)
print("Columnas esperadas  :", len(COLUMNAS_ESPERADAS))

Raíz del proyecto   : proyecto-grupo8-mcdi500
Archivo de la Fase 2: F2/data/processed/yrbs2023_seleccion_procesada.csv
Archivo original    : F1/data/raw/XXH2023_YRBSS_data.csv
Variable objetivo   : salud_mental_cod
Columnas esperadas  : 8

## Preparación del entorno

In [2]:
import os
import io
import sys
import time
import timeit
import inspect
import tracemalloc

import numpy as np
import pandas as pd

np.random.seed(SEMILLA)

# Dos carpetas de código, cada una con su propósito (README, «Dos carpetas src»):
#   src/      -> módulo de F1-F2 (constantes del codebook y carga del archivo original)
#   F3/src/   -> núcleo algorítmico de F3 (clases del pipeline, scripts y mediciones)
for ruta in (RUTA_SRC_F2, RUTA_SRC_F3):
    if str(ruta.resolve()) not in sys.path:
        sys.path.insert(0, str(ruta.resolve()))

import procesamiento as proc                 # F2: fuente única de las constantes
import carga, transformadores, estrategias, pipeline, fabrica, observadores   # F3: núcleo POO
import contingencia, busqueda, analisis, segmentacion                        # F3: núcleo analítico
import medicion, recursion, didacticos                                       # F3: utilidades y ejemplos

print("Python :", sys.version.split()[0])
print("pandas :", pd.__version__)
print("NumPy  :", np.__version__)
print("Semilla:", SEMILLA)
print("Módulo de F2 cargado:", Path(proc.__file__).relative_to(RAIZ).as_posix())
print("Módulos de F3 cargados:", ", ".join(sorted(
    Path(m.__file__).name for m in (carga, transformadores, estrategias, pipeline, fabrica,
                                     observadores, contingencia, busqueda, analisis,
                                     segmentacion, medicion, recursion, didacticos))))

Python : 3.13.15
pandas : 3.0.6
NumPy  : 2.5.3
Semilla: 42
Módulo de F2 cargado: src/procesamiento.py
Módulos de F3 cargados: analisis.py, busqueda.py, carga.py, contingencia.py, didacticos.py, estrategias.py, fabrica.py, medicion.py, observadores.py, pipeline.py, recursion.py, segmentacion.py, transformadores.py

## Carga del conjunto desde el archivo externo

El cuaderno **no genera los datos**: los lee del archivo que se indique en la
configuración. La función de carga (`cargar`, en `F3/src/carga.py`) hace tres cosas antes de
devolver nada:

1. Comprueba que el archivo exista, y si no, explica dónde ponerlo.
2. Lo lee según su extensión, sea CSV o Excel.
3. Verifica que estén las columnas declaradas en la configuración.

Ese tercer paso es el que evita el error más molesto: descubrir en la celda veinte que
una columna se llamaba distinto.

In [3]:
from carga import leer_archivo, verificar_esquema, cargar, perfilar   # F3/src/carga.py

# Las funciones de entrada no conocen el pipeline: reciben una ruta y las columnas esperadas
print(inspect.getsource(verificar_esquema))

def verificar_esquema(df: pd.DataFrame, columnas_esperadas) -> dict:
    """Comprueba que estén todas las columnas declaradas en la configuración."""
    faltantes = [c for c in columnas_esperadas if c not in df.columns]
    if faltantes:
        raise KeyError(
            f"Faltan columnas declaradas en la configuración: {faltantes}\n"
            f"Columnas disponibles en el archivo: {list(df.columns)}"
        )
    sobrantes = [c for c in df.columns if c not in columnas_esperadas]
    return {"declaradas": len(columnas_esperadas),
            "en_archivo": df.shape[1],
            "no_declaradas": sobrantes}

In [4]:
datos = cargar(RUTA_DATOS, COLUMNAS_ESPERADAS, columnas_numericas=COLUMNAS_CONTINUAS, raiz=RAIZ)
datos.head()

Archivo leído: F2/data/processed/yrbs2023_seleccion_procesada.csv
Forma: 20103 filas x 26 columnas
Esquema verificado: 8 columnas declaradas, 18 no declaradas

,id_registro,peso_muestral,estrato,psu,edad_cod,sexo_cod,raceeth_cod,salud_mental_cod,redes_sociales_cod,sueno_cod,...,raza_hawaiana_pacifico,raza_blanca,raza_hispana,raza_multiple_hispana,raza_multiple_no_hispana,sexo_femenino,salud_mental_mala,redes_uso_frecuente,sueno_8h_o_mas,actividad_5_dias
0,1,0.8614,103,16294,3.0,1.0,NaN,1.0,6.0,3.0,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0
1,2,0.8920,103,16294,4.0,2.0,5.0,3.0,4.0,5.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3,0.5081,103,16294,5.0,2.0,5.0,2.0,8.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,4,1.1759,103,16294,6.0,1.0,5.0,3.0,8.0,4.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,5,0.8920,103,16294,3.0,2.0,5.0,3.0,6.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

**Si se obtiene un `KeyError` al cargar**, la configuración no coincide con el archivo. El
mensaje lista las columnas que faltan y las que sí están: corrijan los nombres en la celda
de configuración y vuelvan a ejecutar.

**Las 26 columnas** son las 11 seleccionadas en F2 más 15 derivadas (bandera de faltantes,
8 columnas de raza/etnicidad y 5 indicadores 0/1). Las «no declaradas» son esas derivadas.

## El conjunto antes de tocarlo

Un perfil que funciona con cualquier conjunto, no solo con este (`perfilar`, en `F3/src/carga.py`). Se apoya en la
configuración, así que al cambiar de proyecto sigue sirviendo.

In [5]:
perfil = perfilar(datos)
print("Columnas con valores faltantes:")
print(perfil[perfil["nulos"] > 0].to_string(index=False))

print(f"\nDistribución de la variable objetivo '{COLUMNA_OBJETIVO}':")
print(datos[COLUMNA_OBJETIVO].value_counts(normalize=True).round(4))

for columna in COLUMNAS_NOMINALES:
    print(f"\nCategorías de {columna}:")
    print(datos[columna].value_counts(dropna=False).sort_index())

Columnas con valores faltantes:
                 columna    tipo  unicos  nulos  pct_nulos
      redes_sociales_cod float64       8   4900      24.37
     redes_uso_frecuente float64       2   4900      24.37
       salud_mental_mala float64       2   4398      21.88
        salud_mental_cod float64       5   4398      21.88
               sueno_cod float64       7   2662      13.24
          sueno_8h_o_mas float64       2   2662      13.24
    actividad_fisica_cod float64       8   1227       6.10
        actividad_5_dias float64       2   1227       6.10
          raza_amerindia float64       2    370       1.84
             raceeth_cod float64       8    370       1.84
   raza_multiple_hispana float64       2    370       1.84
raza_multiple_no_hispana float64       2    370       1.84
             raza_blanca float64       2    370       1.84
  raza_hawaiana_pacifico float64       2    370       1.84
            raza_hispana float64       2    370       1.84
           raza_asiatica float64       2    370       1.84
              raza_negra float64       2    370       1.84
                sexo_cod float64       2    158       0.79
           sexo_femenino float64       2    158       0.79
                edad_cod float64       7     98       0.49

Distribución de la variable objetivo 'salud_mental_cod':
salud_mental_cod
3.0    0.3025
4.0    0.2150
2.0    0.2106
1.0    0.1807
5.0    0.0911
Name: proportion, dtype: float64

Categorías de raceeth_cod:
raceeth_cod
1.0    1334
2.0     995
3.0    1791
4.0     105
5.0    9700
6.0    1208
7.0    2786
8.0    1814
NaN     370
Name: count, dtype: int64

Categorías de sexo_cod:
sexo_cod
1.0     9884
2.0    10061
NaN      158
Name: count, dtype: int64

**Tres observaciones que condicionan todo lo que viene (YRBS 2023).**

1. **Hay faltantes reales en todas las variables de análisis**, entre 0,5 % (`edad_cod`) y 24,4 %
   (`redes_sociales_cod`). En la Fase 2 se mostró que no son aleatorios y se decidió **no imputarlos**
   (bitácora 2.5). Aquí la imputación aparece solo como ejemplo didáctico sobre `COLUMNA_IMPUTAR`.
2. **Los códigos son ordinales o nominales, no cantidades.** `sexo_cod` y `raceeth_cod` son nominales:
   un código 6 no «vale más» que un 2. Por eso se codifican con columnas 0/1.
3. **La variable objetivo (`salud_mental_cod`) tiene 21,9 % de faltantes.** No se imputa: la separación
   entrenamiento/prueba se hace solo con los registros que la respondieron (sección 3).

---
# 1. De funciones a objetos: por qué

Así se ve el código de la Fase 2, en celdas sueltas:

In [6]:
# El estilo de la Fase 2: funciona, pero cada celda depende de las anteriores
df_f2 = datos.copy()
df_f2 = df_f2.drop(columns=[COLUMNA_ID])
df_f2[COLUMNA_IMPUTAR] = df_f2[COLUMNA_IMPUTAR].fillna(df_f2[COLUMNA_IMPUTAR].median())
df_f2 = pd.get_dummies(df_f2, columns=["raceeth_cod"], dtype=int)

print("Resultado:", df_f2.shape)

Resultado: (20103, 32)

Funciona. Pero tiene cuatro problemas que aparecen cuando el proyecto crece:

| Problema | Consecuencia |
|---|---|
| El orden importa y no está declarado | Ejecutar una celda fuera de orden produce otro resultado |
| No se puede reutilizar sin copiar | El mismo código se duplica en el cuaderno de F3 y F4 |
| No se puede probar por partes | Si el resultado está mal, hay que revisar todo |
| La mediana se calcula sobre todo el conjunto | Si después separan entrenamiento y prueba, hay **fuga de datos** |

La programación orientada a objetos resuelve los cuatro: cada paso pasa a ser una pieza
con nombre, con estado propio y con una interfaz fija.

---
# 2. La clase `Preprocesador`

Primera versión: una clase que guarda la tabla y sabe prepararla. Cada método hace
**una sola cosa** y devuelve `self`, lo que permite encadenar llamadas.

La clase está en `F3/src/didacticos.py`: la celda muestra su código y la usa.

In [7]:
from didacticos import Preprocesador      # F3/src/didacticos.py

print(inspect.getsource(Preprocesador))

prep = Preprocesador(datos, columna_id=COLUMNA_ID)
prep.quitar_identificador().imputar(COLUMNA_IMPUTAR).codificar(COLUMNAS_NOMINALES)

print("Resultado:", prep.df.shape)
print("\nLo que el objeto recuerda:")
print(prep.informe())

class Preprocesador:
    """Guarda la tabla del proyecto y sabe prepararla para el análisis.

    La tabla vive en self.df. Cada método es un paso del pipeline que trabaja
    sobre esa misma tabla y devuelve self, para poder encadenar.
    """

    def __init__(self, df: pd.DataFrame, columna_id: str = "id_registro"):
        self.df = df.copy()          # copia: no se modifica el original
        self.columna_id = columna_id
        self.registro = []           # lo que el objeto va recordando

    def quitar_identificador(self):
        """El id no aporta información al análisis: identifica, no describe."""
        if self.columna_id in self.df.columns:
            self.df = self.df.drop(columns=[self.columna_id])
            self.registro.append(f"{self.columna_id} eliminado")
        return self

    def imputar(self, columna):
        """Rellena los nulos de una columna con la mediana."""
        nulos = int(self.df[columna].isna().sum())
        mediana = float(self.df[columna].median())
        self.df[columna] = self.df[columna].fillna(mediana)
        self.registro.append(f"{columna}: {nulos} nulos imputados con mediana={mediana:.1f}")
        return self

    def codificar(self, columnas):
        """Convierte columnas de categorías en columnas 0/1."""
        antes = self.df.shape[1]
        self.df = pd.get_dummies(self.df, columns=columnas, dtype=int)
        self.registro.append(f"codificadas {columnas}: {antes} -> {self.df.shape[1]} columnas")
        return self

    def informe(self):
        """Devuelve lo que el objeto recuerda haber hecho."""
        return "\n".join(f"  {i}. {paso}" for i, paso in enumerate(self.registro, 1))

Resultado: (20103, 33)

Lo que el objeto recuerda:
  1. id_registro eliminado
  2. actividad_fisica_cod: 1227 nulos imputados con mediana=5.0
  3. codificadas ['raceeth_cod', 'sexo_cod']: 25 -> 33 columnas

**Lo que ganamos con esto.** El objeto `prep` recuerda qué hizo y con qué valores. En la
Fase 2 esa información había que anotarla a mano en la bitácora; acá es producto de la
ejecución y no puede quedar desactualizada.

**Lo que todavía falta.** Esta clase mezcla dos cosas: aprender de los datos y
aplicarlos. Eso se arregla en la parte siguiente.

---
# 3. Encapsulamiento: proteger el estado interno

El `Preprocesador` de arriba tiene un problema serio: calcula la mediana **sobre el
conjunto completo**. Si después separan entrenamiento y prueba, la mediana ya vio los
datos de prueba. Eso se llama **fuga de datos** y es uno de los errores más caros en
ciencia de datos.

La solución es separar dos momentos:

- **`ajustar`**: aprende los parámetros, y solo del conjunto de entrenamiento.
- **`transformar`**: los aplica a cualquier conjunto.

Y proteger ese estado interno con un guion bajo al inicio del nombre, que en Python
significa «esto es interno, no lo toques desde fuera». La clase de ejemplo, `ImputadorSimple`,
está en `F3/src/didacticos.py`.

In [8]:
from didacticos import ImputadorSimple    # F3/src/didacticos.py

print(inspect.getsource(ImputadorSimple))

# El orden equivocado ahora falla con un mensaje claro
imputador = ImputadorSimple(COLUMNA_IMPUTAR)
try:
    imputador.transformar(datos)
except RuntimeError as error:
    print("RuntimeError:", error)

class ImputadorSimple:
    """Imputa una columna separando lo que aprende de lo que aplica (ejemplo didáctico)."""

    def __init__(self, columna: str = "actividad_fisica_cod"):
        self.columna = columna
        self._mediana = None        # interno: se aprende, no se asigna desde fuera
        self._ajustado = False      # interno: controla el orden de las llamadas

    @property
    def ajustado(self):
        """Solo lectura: se puede consultar, no asignar."""
        return self._ajustado

    @property
    def mediana(self):
        """Mediana aprendida en el ajuste (solo lectura)."""
        return self._mediana

    def ajustar(self, df):
        """Aprende la mediana, solo del conjunto que recibe."""
        self._mediana = float(df[self.columna].median())
        self._ajustado = True
        return self

    def transformar(self, df):
        """Aplica la mediana aprendida sobre una copia de df."""
        if not self._ajustado:
            raise RuntimeError(
                "ImputadorSimple: hay que llamar a ajustar() antes de transformar(). "
                "La mediana se aprende del conjunto de entrenamiento."
            )
        df = df.copy()
        df[self.columna] = df[self.columna].fillna(self._mediana)
        return df

RuntimeError: ImputadorSimple: hay que llamar a ajustar() antes de transformar(). La mediana se aprende del conjunto de entrenamiento.

In [9]:
# El orden correcto, con separación de conjuntos
# La variable objetivo no se imputa (bitácora 2.5): solo se separan los registros
# que la respondieron
datos_objetivo = datos.dropna(subset=[COLUMNA_OBJETIVO])
print(f"Registros con {COLUMNA_OBJETIVO} respondida: {len(datos_objetivo)} de {len(datos)}")

entrenamiento = datos_objetivo.sample(frac=1 - PROPORCION_PRUEBA, random_state=SEMILLA)
prueba = datos_objetivo.drop(index=entrenamiento.index)

imputador = ImputadorSimple(COLUMNA_IMPUTAR).ajustar(entrenamiento)
prueba_lista = imputador.transformar(prueba)

print("Mediana aprendida del entrenamiento:", round(imputador.mediana, 2))
print("Mediana del conjunto de prueba     :", round(prueba[COLUMNA_IMPUTAR].median(), 2))
print("Nulos en prueba después de imputar :", int(prueba_lista[COLUMNA_IMPUTAR].isna().sum()))
if imputador.mediana != prueba[COLUMNA_IMPUTAR].median():
    print("\nSon medianas distintas, y está bien: se usó la del entrenamiento.")
else:
    print("\nAquí coinciden porque el código es discreto (1 a 8), pero el valor usado es el del entrenamiento.")

# La propiedad es de solo lectura
try:
    imputador.ajustado = False
except AttributeError as error:
    print("\nAttributeError:", error)

Registros con salud_mental_cod respondida: 15705 de 20103
Mediana aprendida del entrenamiento: 5.0
Mediana del conjunto de prueba     : 5.0
Nulos en prueba después de imputar : 0

Aquí coinciden porque el código es discreto (1 a 8), pero el valor usado es el del entrenamiento.

AttributeError: property 'ajustado' of 'ImputadorSimple' object has no setter

**Por qué importa.** Sin el control de `_ajustado`, transformar antes de ajustar
produciría un resultado sin sentido **y sin ningún mensaje de error**. El
encapsulamiento convierte un error silencioso en uno visible.

Este bloque es la evidencia del encapsulamiento: atributos internos con guion bajo,
propiedades de solo lectura y validación antes de actuar.

---
# 4. Herencia y polimorfismo

Al mirar el `ImputadorSimple`: el control de `_ajustado`, la copia defensiva y el mensaje de
error van a repetirse en el codificador, en el escalador y en cualquier otro paso.

**Herencia** es escribir eso una sola vez en una clase base. En el proyecto esa clase base es
`Transformador` y **vive en `F3/src/transformadores.py`**: el cuaderno la importa, no la
redefine. Así el código que se prueba aquí es exactamente el que queda en el repositorio.
La celda siguiente muestra su contrato leyendo el código fuente del módulo.

In [10]:
from transformadores import Transformador

# El contrato de la clase base, leído del módulo (no copiado a mano)
print(f"Definida en: F3/src/{Path(inspect.getfile(Transformador)).name}\n")
print(inspect.getsource(Transformador.ajustar))
print(inspect.getsource(Transformador.transformar))

# La clase base no se usa sola: si una hija olvida implementar aprender(), el error lo dice
try:
    Transformador(COLUMNA_IMPUTAR).ajustar(datos)
except NotImplementedError as error:
    print("NotImplementedError:", error)

Definida en: F3/src/transformadores.py

    def ajustar(self, df: pd.DataFrame) -> "Transformador":
        """Valida la entrada, aprende los parámetros y devuelve self."""
        faltan = [c for c in self.columnas_requeridas() if c not in df.columns]
        if faltan:                                  # validar antes de trabajar
            raise KeyError(f"{self.nombre}: no existen las columnas {faltan}.")
        self._parametros = self.aprender(df)        # delega en la clase hija
        self._ajustado = True
        return self                                 # permite encadenar

    def transformar(self, df: pd.DataFrame) -> pd.DataFrame:
        """Aplica lo aprendido sobre una copia; nunca modifica la entrada."""
        if not self._ajustado:
            raise RuntimeError(f"{self.nombre}: hay que ajustar antes de transformar.")
        return self.aplicar(df.copy())              # copia defensiva

NotImplementedError: Cada clase hija debe implementar aprender().

Las clases siguientes son **didácticas**: pasos genéricos (imputar, codificar, escalar, eliminar)
que están en `F3/src/transformadores.py`, separados de los pasos del proyecto en la tupla
`CLASES_DIDACTICAS`. Heredan de la misma `Transformador` y cada una implementa solo `aprender()` y
`aplicar()`. La celda muestra una completa; las demás siguen el mismo molde.

In [11]:
from transformadores import (ImputadorMediana, CodificadorNominal, EscaladorEstandar,
                             EliminadorColumnas, CLASES_DIDACTICAS)

print(inspect.getsource(ImputadorMediana))
print("Pasos didácticos en F3/src/transformadores.py:", [c.__name__ for c in CLASES_DIDACTICAS], "\n")

imp = ImputadorMediana(COLUMNA_IMPUTAR)
salida = imp.ajustar_transformar(datos)
print(imp.nombre, "->", imp.parametros)
print(f"Nulos en {COLUMNA_IMPUTAR} después:", int(salida[COLUMNA_IMPUTAR].isna().sum()))

class ImputadorMediana(Transformador):
    """Rellena los nulos con la mediana aprendida.

    El paréntesis (Transformador) es la HERENCIA: esta clase recibe todo lo
    que tiene Transformador sin volver a escribirlo. Solo implementa los dos
    métodos que le faltaban.
    """

    def aprender(self, df):
        return {"mediana": float(df[self.columna].median()),
                "nulos_en_ajuste": int(df[self.columna].isna().sum())}

    def aplicar(self, df):
        df[self.columna] = df[self.columna].fillna(self._parametros["mediana"])
        return df

Pasos didácticos en F3/src/transformadores.py: ['ImputadorMediana', 'CodificadorNominal', 'EscaladorEstandar', 'EliminadorColumnas', 'ImputadorFlexible']

ImputadorMediana(actividad_fisica_cod) -> {'mediana': 5.0, 'nulos_en_ajuste': 1227}
Nulos en actividad_fisica_cod después: 0

### Cómo comprobar que la herencia funciona

No hay que creer en la herencia: se puede verificar.

In [12]:
imputador = ImputadorMediana(COLUMNA_IMPUTAR)

# 1) El objeto ES un ImputadorMediana Y TAMBIÉN es un Transformador
print("¿Es ImputadorMediana?", isinstance(imputador, ImputadorMediana))
print("¿Es Transformador?   ", isinstance(imputador, Transformador))

# 2) La cadena de búsqueda muestra de dónde hereda
print("\nCadena de herencia:", [c.__name__ for c in ImputadorMediana.__mro__])

# 3) Métodos que NO están escritos en la clase hija y sin embargo funcionan,
#    porque se heredaron de la clase base
print("\nMétodos heredados de Transformador:")
for metodo in ["ajustar", "transformar", "ajustar_transformar"]:
    definido_en = "ImputadorMediana" if metodo in ImputadorMediana.__dict__ else "Transformador"
    print(f"  {metodo:<22} definido en {definido_en}")

print("\nMétodos propios de la clase hija:")
for metodo in ["aprender", "aplicar"]:
    print(f"  {metodo:<22} definido en ImputadorMediana")

¿Es ImputadorMediana? True
¿Es Transformador?    True

Cadena de herencia: ['ImputadorMediana', 'Transformador', 'object']

Métodos heredados de Transformador:
  ajustar                definido en Transformador
  transformar            definido en Transformador
  ajustar_transformar    definido en Transformador

Métodos propios de la clase hija:
  aprender               definido en ImputadorMediana
  aplicar                definido en ImputadorMediana

**Lo que acaban de ver.** `ImputadorMediana` tiene ocho líneas de código propio y
dispone de toda la maquinaria de control de estado. Eso es lo que la herencia ahorra: si
mañana hay que cambiar el mensaje de error, se cambia en un solo lugar y las cuatro
clases hijas lo heredan.

**Polimorfismo** es que quien usa estas clases no necesita saber de qué tipo es cada
una: todas ofrecen `ajustar` y `transformar`.

In [13]:
pasos = [
    EliminadorColumnas(COLUMNA_ID),
    ImputadorMediana(COLUMNA_IMPUTAR),
    CodificadorNominal("raceeth_cod"),
    CodificadorNominal("sexo_cod"),
    EscaladorEstandar(COLUMNA_ESCALAR),
]

resultado = datos.copy()
for paso in pasos:                      # la misma llamada para los cinco
    resultado = paso.ajustar_transformar(resultado)
    print(f"{paso.nombre:<34} -> {resultado.shape}")

EliminadorColumnas(id_registro)    -> (20103, 25)
ImputadorMediana(actividad_fisica_cod) -> (20103, 25)
CodificadorNominal(raceeth_cod)    -> (20103, 32)
CodificadorNominal(sexo_cod)       -> (20103, 33)
EscaladorEstandar(edad_cod)        -> (20103, 33)

**Este bloque es la evidencia de los tres principios:**

- **Herencia**: las cuatro clases heredan de `Transformador` y no repiten el control de estado.
- **Polimorfismo**: el bucle llama `ajustar_transformar()` sin preguntar el tipo.
- **Encapsulamiento**: `_parametros` y `_ajustado` son internos, y hay validación antes de actuar.

La consecuencia práctica: **agregar un transformador nuevo no obliga a tocar el bucle**.
Eso es bajo acoplamiento.

---
# 5. El `Pipeline`: componer los pasos

Una clase que guarda el orden, los ejecuta y controla que se haya ajustado antes de
transformar. Vive en `F3/src/pipeline.py`. Su método interno `_ejecutar_paso()` es el
punto de extensión que `PipelineObservable` redefine en la sección 10 (herencia entre
orquestadores).

In [14]:
from pipeline import Pipeline

print(inspect.getsource(Pipeline.transformar))

pipeline_didactico = Pipeline([
    EliminadorColumnas(COLUMNA_ID),
    ImputadorMediana(COLUMNA_IMPUTAR),
    CodificadorNominal("raceeth_cod"),
    CodificadorNominal("sexo_cod"),
    EscaladorEstandar(COLUMNA_ESCALAR),
    EscaladorEstandar(COLUMNA_IMPUTAR),
])

print(pipeline_didactico)
pipeline_didactico.resumen()

    def transformar(self, df: pd.DataFrame) -> pd.DataFrame:
        """Aplica los pasos en orden sobre una copia de df."""
        if not self._ajustado:
            raise RuntimeError("Pipeline: hay que ajustar antes de transformar.")
        resultado = df.copy()
        for paso in self._pasos:
            resultado = self._ejecutar_paso(paso, resultado)
        return resultado

Pipeline(6 pasos, sin ajustar)

   orden                                     paso               clase
0      1          EliminadorColumnas(id_registro)  EliminadorColumnas
1      2   ImputadorMediana(actividad_fisica_cod)    ImputadorMediana
2      3          CodificadorNominal(raceeth_cod)  CodificadorNominal
3      4             CodificadorNominal(sexo_cod)  CodificadorNominal
4      5              EscaladorEstandar(edad_cod)   EscaladorEstandar
5      6  EscaladorEstandar(actividad_fisica_cod)   EscaladorEstandar

In [15]:
# Ajustar con entrenamiento, transformar prueba: sin fuga de datos
pipeline_didactico.ajustar(entrenamiento)
prueba_lista = pipeline_didactico.transformar(prueba)

print("Entrenamiento:", entrenamiento.shape, " -> Prueba transformada:", prueba_lista.shape)
print(f"\nMedia de {COLUMNA_ESCALAR} en prueba tras escalar:", round(prueba_lista[COLUMNA_ESCALAR].mean(), 4))
print("No es exactamente cero, y está bien: los parámetros vienen del entrenamiento.")

Entrenamiento: (12564, 26)  -> Prueba transformada: (3141, 33)

Media de edad_cod en prueba tras escalar: -0.013
No es exactamente cero, y está bien: los parámetros vienen del entrenamiento.

**Por qué la media no da cero.** El escalador aprendió la media del entrenamiento. Si
diera exactamente cero sobre prueba, significaría que aprendió de datos que no debía
ver. Este resultado es la confirmación de que el diseño está bien.

---
# 6. Cohesión y acoplamiento

Son los dos criterios con los que se evalúa una arquitectura modular. Acá van con código.

**Alta cohesión** significa que cada componente hace **una sola cosa**.

**Bajo acoplamiento** significa que los componentes dependen poco unos de otros: cambiar
uno no obliga a tocar los demás.

## 6.1 Cohesión baja: una clase que hace de todo

Este es el diseño que aparece cuando se escribe rápido. Funciona, pero cada método toca
cosas distintas y la clase no tiene un propósito único. El contraejemplo está en
`F3/src/didacticos.py`.

In [16]:
from didacticos import ProcesadorTodoEnUno    # F3/src/didacticos.py

print(inspect.getsource(ProcesadorTodoEnUno))
print("Cuatro responsabilidades distintas en una sola clase.")
print("Problema práctico: para probar la limpieza hay que tener un archivo real,")
print("porque cargar() y limpiar() viven pegadas en el mismo objeto.")

class ProcesadorTodoEnUno:
    """Ejemplo de COHESIÓN BAJA: hace cuatro cosas sin relación entre sí."""

    def __init__(self, ruta):
        self.ruta = ruta
        self.df = None

    def cargar(self):            # responsabilidad 1: entrada y salida de archivos
        self.df = pd.read_csv(self.ruta)

    def limpiar(self):           # responsabilidad 2: transformar datos
        self.df = self.df.dropna()

    def graficar(self):          # responsabilidad 3: visualización
        pass

    def enviar_correo(self):     # responsabilidad 4: comunicación
        pass

Cuatro responsabilidades distintas en una sola clase.
Problema práctico: para probar la limpieza hay que tener un archivo real,
porque cargar() y limpiar() viven pegadas en el mismo objeto.

## 6.2 Cohesión alta: cada clase con un propósito

El mismo trabajo, repartido. Ahora cada pieza se puede probar sola.

In [17]:
from didacticos import Cargador, Limpiador    # F3/src/didacticos.py

print(inspect.getsource(Cargador))
print(inspect.getsource(Limpiador))

# La ventaja se ve al probar: no hace falta ningún archivo
mini = pd.DataFrame({"a": [1.0, np.nan, 3.0], "b": [4.0, 5.0, 6.0]})
print("Se puede probar el Limpiador sin tocar el disco:")
print("  entrada:", mini.shape, " -> salida:", Limpiador().limpiar(mini).shape)

class Cargador:
    """Una sola responsabilidad: leer datos desde una fuente."""

    def __init__(self, ruta):
        self.ruta = ruta

    def cargar(self):
        return pd.read_csv(self.ruta)

class Limpiador:
    """Una sola responsabilidad: transformar un DataFrame que le entregan.

    NO sabe de dónde vienen los datos. Recibe un DataFrame y
    devuelve otro. Eso es bajo acoplamiento: no depende del Cargador.
    """

    def limpiar(self, df):
        return df.dropna()

Se puede probar el Limpiador sin tocar el disco:
  entrada: (3, 2)  -> salida: (2, 2)

## 6.3 La prueba del acoplamiento

Hay una pregunta que resuelve el asunto sin teoría:

> **Si cambiamos la forma de imputar, ¿cuántos archivos hay que modificar?**

Si la respuesta es **uno**, el acoplamiento es bajo. Si son tres, el diseño es frágil.

Veámoslo con el pipeline que ya construimos.

In [18]:
# Cambiar un paso del pipeline no obliga a tocar ni el Pipeline ni los otros pasos
pipeline_a = Pipeline([EliminadorColumnas(COLUMNA_ID), ImputadorMediana(COLUMNA_IMPUTAR)])
pipeline_b = Pipeline([EliminadorColumnas(COLUMNA_ID), ImputadorMediana("sueno_cod")])

for nombre, pipe in [("versión A", pipeline_a), ("versión B", pipeline_b)]:
    salida = pipe.ajustar(datos).transformar(datos)
    print(f"{nombre}: {salida.shape}")

print("\nSe cambió el paso y NO se modificó la clase Pipeline ni las demás clases.")
print("Eso es bajo acoplamiento.")

versión A: (20103, 25)
versión B: (20103, 25)

Se cambió el paso y NO se modificó la clase Pipeline ni las demás clases.
Eso es bajo acoplamiento.

## 6.4 Cómo se traduce en la estructura de archivos

Una organización con alta cohesión y bajo acoplamiento se reconoce a simple vista. Es la que
tiene hoy el repositorio: cada archivo tiene un propósito que se enuncia en una frase, y la
celda siguiente lo comprueba leyendo la primera línea de la documentación de cada módulo.

| Carpeta | Propósito | Quién la usa |
|---|---|---|
| `src/procesamiento.py` | Módulo de F1–F2: constantes del codebook, carga y validación del archivo original | notebooks de F1 y F2, y `F3/src/fabrica.py` |
| `F3/src/` | Núcleo algorítmico de F3: entrada, clases del pipeline, fábrica, observadores, núcleo analítico, mediciones y ejemplos | este cuaderno |

**La prueba del acoplamiento, aplicada al proyecto:** para cambiar cómo se tratan los
faltantes solo se cambia la estrategia que recibe `TratamientoFaltantes` (sección 16); el
`Pipeline` y los demás pasos no se tocan.

In [19]:
def proposito(modulo):
    """Primera línea útil del docstring del módulo: su propósito en una frase."""
    lineas = [l.strip() for l in (modulo.__doc__ or "").strip().splitlines() if l.strip()]
    return lineas[0].split("—", 1)[-1].strip() if lineas else "sin documentar"


estructura = pd.DataFrame([
    {"archivo": Path(m.__file__).relative_to(RAIZ).as_posix(), "proposito": proposito(m)}
    for m in (proc, carga, transformadores, estrategias, pipeline, fabrica, observadores,
              segmentacion, contingencia, busqueda, analisis, recursion, medicion, didacticos)
])
print(estructura.to_string(index=False))

                  archivo                                                               proposito
     src/procesamiento.py                                    Módulo de preprocesamiento YRBS 2023
          F3/src/carga.py       Entrada de datos: leer el archivo externo y verificar su esquema.
F3/src/transformadores.py                Clase base Transformador y los pasos del pipeline de F2.
    F3/src/estrategias.py                     Tratamiento de valores faltantes (patrón Strategy).
       F3/src/pipeline.py                                    Orquestación del núcleo algorítmico.
        F3/src/fabrica.py Fábricas que arman el pipeline desde la configuración (patrón Factory).
   F3/src/observadores.py                            Observadores del pipeline (patrón Observer).
   F3/src/segmentacion.py            Prevalencia de salud mental no buena por segmentos anidados.
   F3/src/contingencia.py                                        Núcleo algorítmico de la Fase 3.
       F3/src/busqueda.py                            Recuperación de registros por identificador.
       F3/src/analisis.py                     Componente con estado del análisis de contingencia.
      F3/src/recursion.py                  Casos recursivos evaluados y su alternativa iterativa.
       F3/src/medicion.py                           Instrumentos de medición de tiempo y memoria.
     F3/src/didacticos.py          Clases de ejemplo que el cuaderno usa para explicar conceptos.

---
# 7. Validación de las clases base: casos normales, límite y excepciones

Primero se validan las clases didácticas de las secciones 2 a 6. La validación del
**pipeline real del proyecto** está en la sección 15.

In [20]:
# --- CASO NORMAL: el flujo completo sobre el conjunto real ---
pipe = Pipeline([EliminadorColumnas(COLUMNA_ID), ImputadorMediana(COLUMNA_IMPUTAR)])
salida = pipe.ajustar(datos).transformar(datos)

assert len(salida) == len(datos), "El pipeline perdió o duplicó filas"
assert salida[COLUMNA_IMPUTAR].isna().sum() == 0, f"Quedaron nulos en {COLUMNA_IMPUTAR}"
assert COLUMNA_ID not in salida.columns, "El identificador no se eliminó"
print("Caso normal: las tres comprobaciones pasaron.")

Caso normal: las tres comprobaciones pasaron.

In [21]:
# --- CASOS LÍMITE: situaciones extremas pero válidas ---

# 1) Una columna sin ningún nulo no debe alterarse
sin_nulos = pd.DataFrame({COLUMNA_IMPUTAR: [2.0, 5.0, 8.0]})
r1 = ImputadorMediana(COLUMNA_IMPUTAR).ajustar_transformar(sin_nulos)
assert r1[COLUMNA_IMPUTAR].tolist() == [2.0, 5.0, 8.0]
print("Límite 1: columna sin nulos, sin cambios.")

# 2) Una sola categoría genera una sola columna
una_cat = pd.DataFrame({"raceeth_cod": [5.0, 5.0, 5.0]})
r2 = CodificadorNominal("raceeth_cod").ajustar_transformar(una_cat)
print("Límite 2: una categoría ->", list(r2.columns))

# 3) Varianza cero no debe producir división por cero
constante = pd.DataFrame({COLUMNA_ESCALAR: [4.0, 4.0, 4.0]})
r3 = EscaladorEstandar(COLUMNA_ESCALAR).ajustar_transformar(constante)
assert r3[COLUMNA_ESCALAR].notna().all()
print("Límite 3: varianza cero ->", r3[COLUMNA_ESCALAR].tolist())

# 4) Una categoría nueva en prueba no debe crear columna
pipe_cat = Pipeline([CodificadorNominal("sexo_cod")]).ajustar(entrenamiento)
nuevos = prueba.copy()
nuevos.iloc[0, nuevos.columns.get_loc("sexo_cod")] = 9.0      # código que no existe en el codebook
r4 = pipe_cat.transformar(nuevos)
print("Límite 4: categoría nueva no crea columna ->",
      "sexo_cod_9.0" not in r4.columns)

Límite 1: columna sin nulos, sin cambios.
Límite 2: una categoría -> ['raceeth_cod_5.0']
Límite 3: varianza cero -> [0.0, 0.0, 0.0]

Límite 4: categoría nueva no crea columna -> True

In [22]:
# --- EXCEPCIONES: entradas que deben fallar con mensaje claro ---

pruebas = [
    ("transformar sin ajustar", lambda: ImputadorMediana(COLUMNA_IMPUTAR).transformar(datos)),
    ("columna inexistente", lambda: ImputadorMediana("no_existe").ajustar(datos)),
    ("agregar algo que no es Transformador", lambda: Pipeline().agregar("texto")),
    ("pipeline sin ajustar", lambda: Pipeline([ImputadorMediana(COLUMNA_IMPUTAR)]).transformar(datos)),
]

for descripcion, accion in pruebas:
    try:
        accion()
        print(f"  {descripcion:<38} NO lanzó excepción (revisar)")
    except (RuntimeError, KeyError, TypeError) as error:
        print(f"  {descripcion:<38} {type(error).__name__} capturado")

  transformar sin ajustar                RuntimeError capturado
  columna inexistente                    KeyError capturado
  agregar algo que no es Transformador   TypeError capturado
  pipeline sin ajustar                   RuntimeError capturado

---
# 8. Recursividad

Toda función recursiva tiene dos partes: un **caso base** que la detiene y un **caso
recursivo** que reduce el problema y vuelve a llamarse.

**Cuándo se justifica:** cuando no se sabe de antemano cuán profundo es el problema.
Si la profundidad es fija, un bucle es más simple y más rápido.

In [23]:
from recursion import aplanar      # F3/src/recursion.py

metadatos = {
    "proyecto": {"nombre": "YRBS 2023 - redes sociales y salud mental", "fase": 3},
    "datos": {"filas": len(datos), "nulos": {COLUMNA_IMPUTAR: int(datos[COLUMNA_IMPUTAR].isna().sum())}},
    "entorno": {"semilla": SEMILLA, "librerias": {"pandas": pd.__version__}},
}

for clave, valor in aplanar(metadatos).items():
    print(f"{clave:<34} {valor}")

proyecto.nombre                    YRBS 2023 - redes sociales y salud mental
proyecto.fase                      3
datos.filas                        20103
datos.nulos.actividad_fisica_cod   1227
entorno.semilla                    42
entorno.librerias.pandas           3.0.6

**Decisión del proyecto sobre recursividad.** La regla que adoptamos en la Formativa 3 es:
**recursión solo donde la profundidad es desconocida; división funcional en todo lo demás.**

- `aplanar()` la cumple: los metadatos son un diccionario anidado cuya profundidad puede crecer.
- Los pasos de transformación recorren una lista fija de columnas: bucle u operación vectorizada.
- En la Formativa 3 se midió que una recursión que avanza fila por fila falla por límite de
  profundidad sobre ~1.000 filas, y que *divide y vencerás* funciona pero es la más lenta.

El caso recursivo de mayor peso del proyecto está en la **sección 14**: el recorrido de
segmentos anidados, cuya profundidad depende de los datos, y donde la **memoización** evita
repetir trabajo. Reemplaza al ejemplo de Fibonacci de la Formativa 3, que ilustraba el mismo
problema pero no era un cálculo del YRBS.

---
# 9. Eficiencia: medir tiempo y memoria

Las mediciones de este cuaderno son **reproducibles**: usan `timeit` para el tiempo y
`tracemalloc` para la memoria pico, repiten cada medición, comparan implementaciones que
entregan el mismo resultado y se interpretan considerando tiempo **y** memoria. Primero un
ejemplo sobre una sola columna (clasificar horas de sueño); los cálculos del proyecto se
miden en las secciones 12, 13 y 14.

In [24]:
def con_bucle(df):
    """Clasifica las horas de sueño recorriendo las filas una por una.

    Códigos de q85: 1 = ≤4 h, 2 = 5 h, 3 = 6 h, 4 = 7 h, 5 = 8 h, 6 = 9 h, 7 = ≥10 h.
    """
    categorias = []
    for valor in df[COLUMNA_CLASIFICAR]:
        if pd.isna(valor):
            categorias.append("sin dato")
        elif valor < 3:
            categorias.append("muy insuficiente")   # ≤5 h
        elif valor < 5:
            categorias.append("insuficiente")       # 6-7 h
        else:
            categorias.append("suficiente")         # ≥8 h
    return categorias


def vectorizada(df):
    """Lo mismo, con una operación sobre la columna completa."""
    return pd.cut(df[COLUMNA_CLASIFICAR], bins=[-np.inf, 3, 5, np.inf],
                  labels=["muy insuficiente", "insuficiente", "suficiente"],
                  right=False).astype(object).fillna("sin dato").tolist()


# Antes de comparar: comprobar que dan el mismo resultado
assert con_bucle(datos) == vectorizada(datos), "Las versiones no coinciden"
print("Las dos implementaciones producen el mismo resultado.\n")

t_bucle = timeit.timeit(lambda: con_bucle(datos), number=20)
t_vect = timeit.timeit(lambda: vectorizada(datos), number=20)

print(f"Con bucle   : {t_bucle:.4f} s")
print(f"Vectorizada : {t_vect:.4f} s")
print(f"La vectorizada es {t_bucle / t_vect:.1f} veces más rápida")

Las dos implementaciones producen el mismo resultado.

Con bucle   : 0.0906 s
Vectorizada : 0.0479 s
La vectorizada es 1.9 veces más rápida

**La comprobación con `assert` va antes de medir.** Una versión más rápida que entrega otro
resultado no es una optimización: es un error.

In [25]:
from medicion import medir      # F3/src/medicion.py: tiempo y memoria pico de cualquier función

print(inspect.getsource(medir).split('"""')[0] + '"""..."""')

_, s_bucle, m_bucle = medir(con_bucle, datos)
_, s_vect, m_vect = medir(vectorizada, datos)

pd.DataFrame([
    {"version": "con bucle", "segundos": round(s_bucle, 5), "memoria_mb": round(m_bucle, 3)},
    {"version": "vectorizada", "segundos": round(s_vect, 5), "memoria_mb": round(m_vect, 3)},
])

def medir(funcion, *args, **kwargs):
    """..."""

       version  segundos  memoria_mb
0    con bucle   0.02724       0.167
1  vectorizada   0.00745       0.515

**Contraste entre tiempo y espacio.** La versión más rápida consume **más** memoria: `pd.cut`
construye una columna categórica intermedia. Esa tensión se resuelve con la cifra: en el tamaño
real la diferencia es menor a un megabyte.

In [26]:
# Cómo crece el costo con el tamaño: esto es lo que revela la complejidad
mediciones = []
for n in [1000, 5000, 20000, 50000]:
    muestra = datos.sample(n=n, replace=True, random_state=SEMILLA)
    t_b = timeit.timeit(lambda: con_bucle(muestra), number=5) / 5
    t_v = timeit.timeit(lambda: vectorizada(muestra), number=5) / 5
    mediciones.append({"filas": n, "bucle_ms": round(t_b * 1000, 2),
                       "vectorizada_ms": round(t_v * 1000, 2),
                       "razon": round(t_b / t_v, 1)})

tabla = pd.DataFrame(mediciones)
print(tabla.to_string(index=False))
print("\nLa última columna muestra cómo cambia la ventaja con el tamaño.")

 filas  bucle_ms  vectorizada_ms  razon
  1000      0.33            1.27    0.3
  5000      1.40            1.31    1.1
 20000      3.19            2.33    1.4
 50000     10.46            3.78    2.8

La última columna muestra cómo cambia la ventaja con el tamaño.

**Un resultado que conviene mirar con atención.** En los tamaños más pequeños la versión
vectorizada puede resultar **igual o más lenta**. No es un error: `pd.cut` tiene un costo fijo
de preparación que en mil filas pesa más que el ahorro. La ventaja aparece cuando el volumen
crece y ese costo fijo se reparte entre más datos. No basta con reportar qué versión ganó: hay
que decir **bajo qué condiciones**.

**Tres reglas para que la medición valga** (acordadas en el foro de la Formativa 2)

1. **Repetir y conservar el tiempo menor**, no el promedio: los valores altos suelen reflejar
   interrupciones del sistema operativo, no el costo del código.
2. **Medir sobre el tamaño real** del conjunto. En mil filas todo es instantáneo.
3. **Comprobar que las versiones dan el mismo resultado.**

Medir sirve si **cambia una decisión**: ver dónde está el costo y reescribir esa parte.

---
# 10. Patrones de diseño

Un patrón es una solución conocida a un problema que se repite. En esta sección se muestran
los tres que tienen sentido en nuestro proyecto. **El que adoptamos como patrón principal es
Strategy**, aplicado al tratamiento de faltantes (sección 16). Factory y Observer se usan
como apoyo.

## Strategy: varias formas de hacer lo mismo

En la Fase 2 comparamos cuatro formas de tratar los faltantes (conservar, eliminar filas,
moda y mediana) escribiendo un bloque distinto para cada una. Si cada forma es un bloque
distinto, cambiar de una a otra obliga a reescribir. Strategy separa el **qué** del **cómo**.

El ejemplo de esta celda es didáctico (imputación de `actividad_fisica_cod`): las estrategias
genéricas (`PorMediana`, `PorMedia`, `PorMedianaDeGrupo`) están en `F3/src/estrategias.py` e
`ImputadorFlexible`, en `F3/src/transformadores.py`. La versión del proyecto está en la sección 16.

In [27]:
from estrategias import EstrategiaImputacion, PorMediana, PorMedia, PorMedianaDeGrupo
from transformadores import ImputadorFlexible

print(inspect.getsource(ImputadorFlexible))

# Comparación de estrategias didácticas, en un bucle
desv_original = datos[COLUMNA_IMPUTAR].std()
comparacion = []
for estrategia in [PorMediana(), PorMedia(), PorMedianaDeGrupo(COLUMNA_GRUPO)]:
    salida = ImputadorFlexible(COLUMNA_IMPUTAR, estrategia).ajustar_transformar(datos)
    comparacion.append({
        "estrategia": estrategia.etiqueta,
        "desv_antes": round(desv_original, 4),
        "desv_despues": round(salida[COLUMNA_IMPUTAR].std(), 4),
        "cambio_pct": round((salida[COLUMNA_IMPUTAR].std() - desv_original) / desv_original * 100, 2),
    })

pd.DataFrame(comparacion)

class ImputadorFlexible(Transformador):
    """No sabe imputar: sabe cuándo. El cómo lo aporta la estrategia (Strategy)."""

    def __init__(self, columna: str, estrategia=None):
        super().__init__(columna)          # llama al constructor de la clase base
        self.estrategia = estrategia or PorMediana()

    def aprender(self, df):
        return {"valor": self.estrategia.calcular(df, self.columna),
                "estrategia": self.estrategia.etiqueta}

    def aplicar(self, df):
        valor = self._parametros["valor"]
        if isinstance(valor, dict):                       # mediana por grupo
            relleno = df[self.estrategia.columna_grupo].map(valor)
            df[self.columna] = df[self.columna].fillna(relleno)
            df[self.columna] = df[self.columna].fillna(df[self.columna].median())
        else:
            df[self.columna] = df[self.columna].fillna(valor)
        return df

          estrategia  desv_antes  desv_despues  cambio_pct
0            mediana       2.503        2.4254       -3.10
1              media       2.503        2.4254       -3.10
2  mediana por grupo       2.503        2.4319       -2.84

**Nota sobre estos números (YRBS).** `actividad_fisica_cod` es un código discreto de 1 a 8, por lo que
la mediana y la media no coinciden y cada estrategia reduce la dispersión en distinta medida. Es solo una
comparación didáctica: en el proyecto **no se imputa** esta variable (bitácora 2.5).

Toda
imputación por un valor central reduce la dispersión; lo que se compara es **cuánto**, y
esa cifra es el argumento para elegir.

## Factory: decidir qué construir

La transformación que corresponde depende del rol de la variable. Factory concentra esa
decisión en un solo lugar, en vez de repetirla en cada cuaderno. Las fábricas están en
`F3/src/fabrica.py`: `crear_transformador()` (didáctica) y `construir_pipeline_proyecto()` (sección 11).

In [28]:
from fabrica import crear_transformador     # F3/src/fabrica.py

print(inspect.getsource(crear_transformador))

# El diccionario de variables de la Fase 1 pasa a gobernar el pipeline
diccionario = [
    {"variable": COLUMNA_ID, "rol": "identificador"},
    {"variable": COLUMNA_IMPUTAR, "rol": "continua"},
    {"variable": "raceeth_cod", "rol": "nominal"},
    {"variable": "sexo_cod", "rol": "nominal"},
    {"variable": COLUMNA_ESCALAR, "rol": "escalar"},
]

pipeline_auto = Pipeline([crear_transformador(v["rol"], v["variable"]) for v in diccionario])
salida = pipeline_auto.ajustar(datos).transformar(datos)

print(pipeline_auto.resumen().to_string(index=False))
print("\nResultado:", salida.shape)

try:
    crear_transformador("geografica", "estrato")
except ValueError as error:
    print("\nValueError:", error)

def crear_transformador(rol: str, columna: str, **parametros):
    """Devuelve el transformador que corresponde al rol analítico."""
    rol = rol.strip().lower()

    if rol == "continua":
        return ImputadorFlexible(columna, parametros.get("estrategia"))
    if rol == "nominal":
        return CodificadorNominal(columna)
    if rol == "escalar":
        return EscaladorEstandar(columna)
    if rol == "identificador":
        return EliminadorColumnas(columna)

    raise ValueError(
        f"Rol desconocido: '{rol}'. "
        "Roles válidos: continua, nominal, escalar, identificador."
    )

 orden                                    paso              clase
     1         EliminadorColumnas(id_registro) EliminadorColumnas
     2 ImputadorFlexible(actividad_fisica_cod)  ImputadorFlexible
     3         CodificadorNominal(raceeth_cod) CodificadorNominal
     4            CodificadorNominal(sexo_cod) CodificadorNominal
     5             EscaladorEstandar(edad_cod)  EscaladorEstandar

Resultado: (20103, 33)

ValueError: Rol desconocido: 'geografica'. Roles válidos: continua, nominal, escalar, identificador.

## Observer: registrar sin estorbar

La bitácora de decisiones suele escribirse a mano después de ejecutar, con el riesgo de
quedar desactualizada. Con Observer, el pipeline **avisa** cada vez que termina un paso
y quien quiera registrar se suscribe. Los observadores están en `F3/src/observadores.py`.

In [29]:
from pipeline import PipelineObservable              # F3/src/pipeline.py
from observadores import Bitacora, ReporteConsola     # F3/src/observadores.py

# PipelineObservable hereda de Pipeline y solo redefine el punto de extensión
print("Cadena de herencia:", [c.__name__ for c in PipelineObservable.__mro__])
print("Redefine:", [m for m in ("transformar", "_ejecutar_paso") if m in PipelineObservable.__dict__], "\n")

bitacora = Bitacora()
pipe = PipelineObservable([
    EliminadorColumnas(COLUMNA_ID),
    ImputadorFlexible(COLUMNA_IMPUTAR),
    CodificadorNominal("raceeth_cod"),
    EscaladorEstandar(COLUMNA_ESCALAR),
])
pipe.suscribir(bitacora).suscribir(ReporteConsola())

print("Ejecución del pipeline:")
salida = pipe.ajustar(datos).transformar(datos)

print("\nBitácora producida por la propia ejecución:")
bitacora.a_dataframe()[["paso", "filas", "columnas", "segundos"]]

Cadena de herencia: ['PipelineObservable', 'Pipeline', 'object']
Redefine: ['_ejecutar_paso']

Ejecución del pipeline:
  EliminadorColumnas(id_registro)               20103 filas,  25 col  [0.0007s]
  ImputadorFlexible(actividad_fisica_cod)       20103 filas,  25 col  [0.0007s]
  CodificadorNominal(raceeth_cod)               20103 filas,  32 col  [0.0049s]
  EscaladorEstandar(edad_cod)                   20103 filas,  32 col  [0.0015s]

Bitácora producida por la propia ejecución:

                                      paso  filas  columnas  segundos
0          EliminadorColumnas(id_registro)  20103        25   0.00069
1  ImputadorFlexible(actividad_fisica_cod)  20103        25   0.00066
2          CodificadorNominal(raceeth_cod)  20103        32   0.00486
3              EscaladorEstandar(edad_cod)  20103        32   0.00153

**Qué acaba de pasar.** La bitácora no se escribió a mano: se genera cada vez que el pipeline
corre, así que no puede quedar desactualizada. Y `PipelineObservable` no repite el recorrido de
los pasos: lo hereda de `Pipeline` y solo redefine `_ejecutar_paso()`.

## Resumen: qué patrón usamos y por qué

| Patrón | El problema que resuelve | Dónde se usa en el proyecto |
|---|---|---|
| **Strategy** (principal) | Varias formas de tratar los faltantes | `TratamientoFaltantes` + `ConservarFaltantes` (sección 16) |
| **Factory** (apoyo) | Armar el pipeline desde las constantes declaradas | `construir_pipeline_proyecto()` en `fabrica.py` (sección 11) |
| **Observer** (apoyo) | Registrar cada paso sin que el pipeline sepa quién anota | `PipelineObservable` + `Bitacora` en `observadores.py` (secciones 11 y 17) |

**Por qué no Singleton.** La configuración del proyecto ya está en una sola celda y en las
constantes de `src/procesamiento.py`. Un Singleton agregaría estado global, que complica las
pruebas, sin resolver un problema que tengamos.

---
# 11. El núcleo algorítmico: el pipeline de la Fase 2 en clases

Hasta acá los ejemplos fueron didácticos. Esta sección usa **cada paso real** del notebook de
la Fase 2 convertido en una clase hija de `Transformador`. Las clases están en
`F3/src/transformadores.py`; las constantes (columnas, escalas del codebook) no se copian: se
importan de `src/procesamiento.py`, el mismo módulo que usó la Fase 2.

| Paso en la Fase 2 (función o celda) | Clase en la Fase 3 | Decisión (bitácora) |
|---|---|---|
| Eliminar `orig_rec` tras comprobar 100 % de nulos | `EliminadorColumnaVacia` | 2.1 |
| `proc.seleccionar_columnas()` | `SeleccionadorColumnas` | 2.3 |
| Bandera `n_faltantes_analisis` / `caso_completo` | `MarcadorFaltantes` | 2.5 |
| No imputar ni eliminar filas | `TratamientoFaltantes` + `ConservarFaltantes` (Strategy) | 2.5 |
| `castear_codigos()` | `CastearCodigos` | 2.4 |
| `proc.transformar_datos()` | `ConversorOrdinal` | 2.4 |
| `codificar_one_hot()` | `CodificadorOneHot` | 2.7 |
| `crear_indicador()` | `IndicadorBinario` (ejercicio 1) | 2.7 |

Todas heredan el control de estado de `Transformador` y solo implementan `aprender()` y
`aplicar()`. Las que trabajan con varias columnas redefinen `columnas_requeridas()`.

In [30]:
from transformadores import (EliminadorColumnaVacia, SeleccionadorColumnas, MarcadorFaltantes,
                             TratamientoFaltantes, CastearCodigos, ConversorOrdinal,
                             CodificadorOneHot, IndicadorBinario, CLASES_PROYECTO)

# Las ocho clases del proyecto, con su responsabilidad leída del docstring
pd.DataFrame([
    {"clase": c.__name__,
     "hereda_de": c.__base__.__name__,
     "redefine_columnas_requeridas": "columnas_requeridas" in c.__dict__,
     "responsabilidad": (c.__doc__ or "").strip().splitlines()[0]}
    for c in CLASES_PROYECTO
])

,clase,hereda_de,redefine_columnas_requeridas,responsabilidad
0,EliminadorColumnaVacia,Transformador,False,Elimina una columna solo si está 100 % vacía (...
1,SeleccionadorColumnas,Transformador,True,Selecciona y renombra las columnas de análisis...
2,MarcadorFaltantes,Transformador,True,Agrega la bandera de faltantes: cuántas variab...
3,TratamientoFaltantes,Transformador,True,No sabe tratar faltantes: sabe cuándo hacerlo....
4,CastearCodigos,Transformador,True,"Convierte códigos float64 a entero Int64, cons..."
5,ConversorOrdinal,Transformador,True,Declara el orden de las escalas ordinales con ...
6,CodificadorOneHot,Transformador,False,Codifica una nominal en columnas 0/1 con nombr...
7,IndicadorBinario,Transformador,False,Crea una columna 0/1 que vale 1 si el código e...

In [31]:
# Un paso completo, tal como está en el módulo: aprender() valida y aplicar() transforma
print(inspect.getsource(MarcadorFaltantes))

class MarcadorFaltantes(Transformador):
    """Agrega la bandera de faltantes: cuántas variables faltan y si el caso está completo."""

    def __init__(self, columnas):
        super().__init__("bandera de faltantes")
        self.columnas = list(columnas)

    def columnas_requeridas(self):
        return self.columnas

    def aprender(self, df):
        completos = int(df[self.columnas].notna().all(axis=1).sum())
        return {"variables": len(self.columnas), "casos_completos": completos}

    def aplicar(self, df):
        # Versión vectorizada: la que ganó la medición (notebook, sección 12)
        df["n_faltantes_analisis"] = df[self.columnas].isna().sum(axis=1).astype("int8")
        df["caso_completo"] = (df["n_faltantes_analisis"] == 0).astype("int8")
        return df

## Ejercicio 1 · Encapsular un paso de nuestro pipeline: `IndicadorBinario`

En la Fase 2, `crear_indicador()` era una función suelta que se llamaba cinco veces. Ahora es
una clase hija de `Transformador` (en `F3/src/transformadores.py`):

- **Herencia:** recibe de la base el control de estado, la validación de columnas y la copia defensiva.
- **Encapsulamiento:** los valores positivos y el porcentaje calculado quedan en `_parametros`, de solo lectura.
- **Regla del proyecto que se mantiene:** un faltante sigue siendo `<NA>`, nunca se convierte en 0.

La prueba de que funciona: el indicador que produce la clase debe ser igual a la columna
`salud_mental_mala` que dejó la Fase 2.

In [32]:
print(inspect.getsource(IndicadorBinario.aplicar))

# Prueba con nuestros datos: salud mental no buena = códigos 4 y 5 (Most of the time, Always)
paso = IndicadorBinario("salud_mental_cod", [4, 5], "salud_mental_mala_f3")
salida = paso.ajustar_transformar(datos)

print(paso.nombre, "->", paso.parametros)
print("Nulos en el origen     :", int(datos["salud_mental_cod"].isna().sum()))
print("Nulos en el indicador  :", int(salida["salud_mental_mala_f3"].isna().sum()), "(se conservan)")

coincide = salida["salud_mental_mala_f3"].astype("float").equals(datos["salud_mental_mala"].astype("float"))
print("¿Igual a la columna de la Fase 2?", coincide)
assert coincide, "El indicador de la clase no coincide con el de la Fase 2"

    def aplicar(self, df):
        codigos = self._codigos(df)
        indicador = codigos.isin(self.valores_positivos).astype("Int8")
        indicador[codigos.isna()] = pd.NA
        df[self.nuevo_nombre] = indicador
        return df

IndicadorBinario(salud_mental_cod) -> {'positivos': [4, 5], 'pct_positivos': 30.6}
Nulos en el origen     : 4398
Nulos en el indicador  : 4398 (se conservan)
¿Igual a la columna de la Fase 2? True

## Strategy aplicado al proyecto: el tratamiento de faltantes

Las estrategias de faltantes están en `F3/src/estrategias.py`. La estrategia del proyecto es
`ConservarFaltantes`: no cambia ningún valor. Aun así se declara como un paso explícito, para
que la decisión de la bitácora 2.5 quede **dentro del código** y no solo en un documento. La
justificación del patrón y la comparación entre estrategias están en la sección 16.

In [33]:
from estrategias import EstrategiaFaltantes, ConservarFaltantes, RellenarModa, RellenarMediana

print("Estrategias disponibles:",
      [c.etiqueta for c in EstrategiaFaltantes.__subclasses__()])
print()
print(inspect.getsource(TratamientoFaltantes.aplicar))

Estrategias disponibles: ['conservar NA', 'moda', 'mediana']

    def aplicar(self, df):
        for columna in self.columnas:
            df[columna] = self.estrategia.tratar(df[columna])   # polimorfismo
        return df

## Ejercicio 2 · Armar el pipeline completo del proyecto

`construir_pipeline_proyecto()` es una **fábrica** (Factory): arma los pasos a partir de las
constantes declaradas en `src/procesamiento.py` y está en `F3/src/fabrica.py`. El orden es el mismo de la
Fase 2, y cada paso tiene su razón:

1. eliminar `orig_rec`, que está vacía;
2. seleccionar y renombrar las 11 columnas;
3. marcar los faltantes **antes** de cualquier cambio de tipo, sobre los valores originales;
4. tratar los faltantes con la estrategia elegida (conservarlos);
5. convertir los códigos a entero y declarar el orden de las ordinales;
6. crear las columnas derivadas: raza/etnicidad 0/1 y los cinco indicadores.

**Por qué aquí no se separa entrenamiento y prueba.** El proyecto es exploratorio: busca una
asociación, no entrena un modelo. Además, ningún paso aprende un valor de los datos que luego
cambie otros datos (solo validan o usan valores declarados del codebook), así que no hay riesgo
de fuga de datos. Por eso el pipeline se ajusta y se aplica sobre el conjunto completo.

In [34]:
from fabrica import (construir_pipeline_proyecto, RAZA, INDICADORES, VARIABLES_ANALISIS)

# El pipeline parte del ARCHIVO ORIGINAL del CDC, igual que la Fase 2
original = proc.cargar_datos(str(RUTA_ORIGINAL))
print(f"Archivo original: {original.shape[0]} filas x {original.shape[1]} columnas\n")

pipeline_proyecto = construir_pipeline_proyecto(observable=True)
bitacora_proyecto = Bitacora()
pipeline_proyecto.suscribir(bitacora_proyecto).suscribir(ReporteConsola())

print(f"Pipeline con {len(pipeline_proyecto)} pasos. Ejecución:")
proyecto = pipeline_proyecto.ajustar(original).transformar(original)
print(f"\nResultado: {proyecto.shape[0]} filas x {proyecto.shape[1]} columnas")

Archivo original: 20103 filas x 117 columnas

Pipeline con 12 pasos. Ejecución:

  EliminadorColumnaVacia(orig_rec)              20103 filas, 116 col  [0.0141s]
  SeleccionadorColumnas(columnas de análisis)   20103 filas,  11 col  [0.0035s]
  MarcadorFaltantes(bandera de faltantes)       20103 filas,  13 col  [0.0055s]
  TratamientoFaltantes(faltantes)               20103 filas,  13 col  [0.0011s]
  CastearCodigos(códigos a Int64)               20103 filas,  13 col  [0.0035s]
  ConversorOrdinal(escalas ordinales)           20103 filas,  13 col  [0.0026s]
  CodificadorOneHot(raceeth_cod)                20103 filas,  21 col  [0.0053s]
  IndicadorBinario(sexo_cod)                    20103 filas,  22 col  [0.0059s]
  IndicadorBinario(salud_mental_cod)            20103 filas,  23 col  [0.0059s]
  IndicadorBinario(redes_sociales_cod)          20103 filas,  24 col  [0.0064s]
  IndicadorBinario(sueno_cod)                   20103 filas,  25 col  [0.0062s]
  IndicadorBinario(actividad_fisica_cod)        20103 filas,  26 col  [0.0067s]

Resultado: 20103 filas x 26 columnas

In [35]:
# Lo que aprendió cada paso: queda registrado por la propia ejecución
pd.DataFrame([
    {"orden": i, "paso": p.nombre, "parametros": p.parametros}
    for i, p in enumerate(pipeline_proyecto.pasos_ejecutados(), start=1)
])

,orden,paso,parametros
0,1,EliminadorColumnaVacia(orig_rec),{'pct_nulos': 100.0}
1,2,SeleccionadorColumnas(columnas de análisis),"{'columnas_entrada': 116, 'columnas_salida': 11}"
2,3,MarcadorFaltantes(bandera de faltantes),"{'variables': 7, 'casos_completos': 10941}"
3,4,TratamientoFaltantes(faltantes),"{'estrategia': 'conservar NA', 'nulos_antes': ..."
4,5,CastearCodigos(códigos a Int64),{'columnas': 7}
5,6,ConversorOrdinal(escalas ordinales),"{'escalas': {'edad_cod': 7, 'redes_sociales_co..."
6,7,CodificadorOneHot(raceeth_cod),"{'columnas_nuevas': ['raza_amerindia', 'raza_a..."
7,8,IndicadorBinario(sexo_cod),"{'positivos': [1], 'pct_positivos': 49.6}"
8,9,IndicadorBinario(salud_mental_cod),"{'positivos': [4, 5], 'pct_positivos': 30.6}"
9,10,IndicadorBinario(redes_sociales_cod),"{'positivos': [6, 7, 8], 'pct_positivos': 78.1}"
10,11,IndicadorBinario(sueno_cod),"{'positivos': [5, 6, 7], 'pct_positivos': 23.0}"
11,12,IndicadorBinario(actividad_fisica_cod),"{'positivos': [6, 7, 8], 'pct_positivos': 48.0}"

**Qué muestra esta tabla.** Cada fila es un objeto distinto, pero el pipeline los recorrió a
todos con las mismas dos llamadas (`ajustar` y `transformar`) sin preguntar de qué tipo eran.
Eso es **polimorfismo** aplicado a nuestro propio pipeline. Y agregar un paso nuevo (por ejemplo,
un indicador más) no obliga a tocar la clase `Pipeline`: solo se agrega una línea en la fábrica.

---
# 12. Ejercicio 3 · Eficiencia sobre un paso real: contar faltantes por fila

El paso `MarcadorFaltantes` cuenta, para cada uno de los 20.103 estudiantes, cuántas de las 7
variables de análisis están vacías. Hay tres formas de escribirlo:

| Versión | Cómo trabaja |
|---|---|
| `con_bucle` | Recorre las filas una por una con `itertuples()` y cuenta en Python |
| `con_apply` | `DataFrame.apply(..., axis=1)`: parece vectorizado, pero llama a una función de Python por cada fila |
| `vectorizada` | `isna().sum(axis=1)`: una sola operación sobre la tabla completa, ejecutada en C por NumPy |

Las tres tienen la misma complejidad teórica, **O(n·k)** (n filas, k = 7 columnas): todas miran
cada celda una vez. Lo que cambia es el **costo por celda**, y eso es lo que se mide.

In [36]:
seleccion = SeleccionadorColumnas(proc.COLUMNAS_ANALISIS).ajustar_transformar(
    EliminadorColumnaVacia("orig_rec").ajustar_transformar(original))


def con_bucle(df, columnas=VARIABLES_ANALISIS):
    """Cuenta faltantes fila por fila, en Python puro."""
    return [sum(1 for valor in fila if pd.isna(valor))
            for fila in df[columnas].itertuples(index=False)]


def con_apply(df, columnas=VARIABLES_ANALISIS):
    """Cuenta faltantes con apply por fila: una llamada de Python por cada fila."""
    return df[columnas].apply(lambda fila: int(fila.isna().sum()), axis=1).tolist()


def vectorizada(df, columnas=VARIABLES_ANALISIS):
    """Cuenta faltantes con una operación sobre la tabla completa."""
    return df[columnas].isna().sum(axis=1).tolist()


# 1) Antes de medir: las tres versiones deben dar EXACTAMENTE el mismo resultado
assert con_bucle(seleccion) == con_apply(seleccion) == vectorizada(seleccion), \
    "Las versiones no coinciden"
print("Las tres versiones producen el mismo conteo en las", len(seleccion), "filas.\n")

# 2) Tiempo: se repite y se conserva el MENOR (regla de la sección 9)
filas_tiempo = []
for funcion in (con_bucle, con_apply, vectorizada):
    mejor = min(timeit.repeat(lambda: funcion(seleccion), number=1, repeat=5))
    _, _, memoria = medir(funcion, seleccion)
    filas_tiempo.append({"version": funcion.__name__, "ms": round(mejor * 1000, 2),
                         "memoria_pico_mb": round(memoria, 3)})

comparacion_faltantes = pd.DataFrame(filas_tiempo)
comparacion_faltantes["veces_mas_lenta"] = (
    comparacion_faltantes["ms"] / comparacion_faltantes["ms"].min()).round(1)
comparacion_faltantes

Las tres versiones producen el mismo conteo en las 20103 filas.

       version      ms  memoria_pico_mb  veces_mas_lenta
0    con_bucle   30.92            1.252             16.5
1    con_apply  487.18            3.437            260.5
2  vectorizada    1.87            1.212              1.0

In [37]:
# 3) Cómo crece el costo con el tamaño del conjunto
crecimiento = []
for n in [1_000, 5_000, 20_103, 40_000]:
    muestra = seleccion.sample(n=n, replace=n > len(seleccion), random_state=SEMILLA)
    fila = {"filas": n}
    for funcion in (con_bucle, con_apply, vectorizada):
        fila[f"{funcion.__name__}_ms"] = round(
            min(timeit.repeat(lambda: funcion(muestra), number=1, repeat=3)) * 1000, 2)
    crecimiento.append(fila)

tabla_crecimiento = pd.DataFrame(crecimiento)
tabla_crecimiento["apply / vectorizada"] = (
    tabla_crecimiento["con_apply_ms"] / tabla_crecimiento["vectorizada_ms"]).round(0)
print(tabla_crecimiento.to_string(index=False))

 filas  con_bucle_ms  con_apply_ms  vectorizada_ms  apply / vectorizada
  1000          1.99         24.97            0.53                 47.0
  5000          7.45        145.61            1.37                106.0
 20103         28.41        505.28            1.85                273.0
 40000         53.84       1033.18            3.56                290.0

**Interpretación.** Los números exactos cambian de un computador a otro, pero el patrón se repite:

1. **Las tres versiones crecen de forma lineal**: si se duplican las filas, el tiempo se duplica
   aproximadamente. Eso confirma la complejidad O(n·k) de las tres.
2. **La diferencia está en la constante.** `vectorizada` hace el trabajo en C sobre la tabla
   completa; `con_bucle` lo hace en Python, celda por celda; y `con_apply` es **la más lenta**
   porque además crea un objeto `Series` por cada fila. Es un resultado que sorprende: `apply`
   *parece* vectorizado, pero no lo es.
3. **Memoria.** En nuestra medición la versión vectorizada fue también la de menor pico de
   memoria, y `con_apply` la de mayor, porque crea un objeto por cada fila. No siempre es así:
   la versión vectorizada arma una tabla temporal de verdadero/falso del tamaño de las 7
   columnas, que con conjuntos mucho más grandes podría pesar. Con 20.103 filas esa tabla es
   pequeña y no hay tensión entre tiempo y memoria.

**Decisión.** `MarcadorFaltantes` usa la versión vectorizada. La medición **cambió una decisión**:
descartamos `apply`, que era la forma que habríamos escrito por intuición.

---
# 13. Integración del avance formativo: tabla de contingencia y búsqueda

En la Formativa 3 escribimos el núcleo analítico como funciones en `F3/src/`. Aquí se
**reutilizan sin copiarlas** y se vuelven a medir en esta ejecución, con la utilidad
`comparar()` de `F3/src/medicion.py`, que antes de medir exige que todas las versiones
entreguen el mismo resultado.

**13.1 Tabla de contingencia q80 × q84.** Cuatro implementaciones del mismo conteo, todas
O(n) en teoría; la diferencia está en la constante por fila.

In [38]:
from contingencia import (preparar_pares, contar_iterrows, contar_zip,
                          contar_crosstab, contar_bincount)
from medicion import comparar

X, Y = "redes_sociales_cod", "salud_mental_cod"
pares = preparar_pares(datos, X, Y)
print(f"Pares válidos {X} × {Y}: {len(pares)} de {len(datos)}\n")

eficiencia_contingencia = comparar(
    {"iterrows": contar_iterrows, "zip": contar_zip,
     "crosstab": contar_crosstab, "bincount": contar_bincount},
    pares, X, Y, repeticiones=5)
eficiencia_contingencia

Pares válidos redes_sociales_cod × salud_mental_cod: 11602 de 20103

  implementacion  tiempo_min_ms  memoria_pico_kib  veces_mas_lenta
0       bincount          0.070             454.0              1.0
1            zip          1.824               2.7             26.1
2       crosstab          5.385             877.6             76.9
3       iterrows        168.197              50.2           2402.8

In [39]:
from analisis import AnalisisContingencia

# La clase de la Formativa 3 usa la implementación adoptada (bincount)
analisis_q80_q84 = AnalisisContingencia(datos, X, Y)
analisis_q80_q84.calcular(metodo="bincount")
proporciones = analisis_q80_q84.proporcion([4, 5])
proporciones["etiqueta"] = proporciones["nivel_x"].map(proc.ETIQUETAS_REDES)
print(analisis_q80_q84)
proporciones[["nivel_x", "etiqueta", "n", "positivos", "porcentaje"]]

AnalisisContingencia(redes_sociales_cod × salud_mental_cod, n=11602, bincount)

   nivel_x                 etiqueta     n  positivos  porcentaje
0        1                   No usa   784        159        20.3
1        2        Unas veces al mes   307         54        17.6
2        3      Una vez a la semana   175         38        21.7
3        4   Unas veces a la semana   537        139        25.9
4        5           Una vez al día   674        166        24.6
5        6      Varias veces al día  4587       1394        30.4
6        7         Una vez por hora   856        277        32.4
7        8  Más de una vez por hora  3682       1300        35.3

**13.2 Búsqueda de un registro por identificador.** Se recuperan 1.000 estudiantes al azar
con tres estrategias; las tres deben devolver las mismas posiciones.

In [40]:
from busqueda import buscar_lineal, buscar_binaria_rec, construir_indice, buscar_en_indice

ids = np.sort(datos[COLUMNA_ID].to_numpy())
consultas = np.random.default_rng(SEMILLA).choice(ids, size=1_000, replace=False)
indice = construir_indice(ids)


def lote_lineal(consultas):
    return [buscar_lineal(ids, c) for c in consultas]


def lote_binaria(consultas):
    return [buscar_binaria_rec(ids, c) for c in consultas]


def lote_indice(consultas):
    return [buscar_en_indice(indice, c) for c in consultas]


eficiencia_busqueda = comparar({"lineal O(n)": lote_lineal,
                                "binaria recursiva O(log n)": lote_binaria,
                                "diccionario O(1)": lote_indice},
                               consultas, repeticiones=3)

# Memoria adicional de cada estructura: el índice cambia tiempo por espacio
_, _, memoria_indice = medir(construir_indice, ids)
print(f"Memoria para construir el diccionario: {memoria_indice:.3f} MB "
      f"(el arreglo ordenado ocupa {ids.nbytes / 1024 / 1024:.3f} MB)\n")
eficiencia_busqueda

Memoria para construir el diccionario: 1.699 MB (el arreglo ordenado ocupa 0.153 MB)

,implementacion,tiempo_min_ms,memoria_pico_kib,veces_mas_lenta
0,diccionario O(1),0.124,8.9,1.0
1,binaria recursiva O(log n),2.675,40.4,21.6
2,lineal O(n),637.763,36.8,5143.2

**Interpretación de 13.1 y 13.2.**

- **Contingencia.** Las cuatro versiones son O(n), pero la constante por fila decide: `iterrows`
  construye un objeto `Series` por fila y es miles de veces más lenta que `bincount`, que
  convierte cada par en un índice entero y cuenta todo en una sola pasada de código compilado.
  `crosstab`, la opción idiomática de pandas, paga el costo de construir un `DataFrame` con
  índices y queda detrás de `zip`. En memoria, `zip` es la más austera (solo el diccionario de
  40 celdas); `bincount` reserva arreglos temporales del tamaño de los pares, del orden de
  0,5 MB, un costo aceptable para la ganancia de tiempo. **Se mantiene `bincount`**, con
  `crosstab` como verificación independiente.
- **Búsqueda.** La lineal recorre en promedio la mitad del arreglo por consulta; la binaria
  recursiva descarta la mitad en cada llamada (profundidad ⌈log₂ 20.103⌉ = 15, lejos del límite de
  la pila); el diccionario responde en tiempo constante. El diccionario gana en tiempo pero cambia
  tiempo por espacio: ocupa del orden de diez veces más memoria que el arreglo ordenado. Como las
  auditorías del proyecto consultan muchos registros sobre el mismo conjunto, **se adopta el
  diccionario**; la binaria queda como alternativa si la memoria llegara a ser una restricción.
- **Resultado analítico.** La tabla reproduce el hallazgo de la Formativa 3: la proporción de
  salud mental no buena sube de 20,3 % entre quienes no usan redes a 35,3 % entre quienes las usan
  más de una vez por hora (muestral, sin ponderar).

---
# 14. Recursión con memoización: prevalencia de salud mental por segmentos

**El problema del proyecto.** La tabla de la sección 13 muestra que la salud mental no buena
sube con la frecuencia de uso de redes. La pregunta siguiente es si ese patrón se mantiene
**dentro** de cada sexo y cada edad. Para responderla se desciende por una jerarquía
(`JERARQUIA_SEGMENTOS`: redes → sexo → edad) y en cada segmento se calcula el porcentaje de
estudiantes con salud mental no buena (q84 = 4–5).

**Por qué recursión.** Un segmento solo se subdivide si tiene al menos `N_MINIMO_SEGMENTO`
estudiantes: con menos, un porcentaje no es interpretable. Por esa poda, la profundidad de cada
rama **depende de los datos** y no se conoce al escribir el código, que es justamente el
criterio del proyecto para usar recursión (sección 8).

**Por qué memoización.** El subconjunto de un segmento se define de forma recursiva: es el
subconjunto de su padre filtrado por un valor más. Sin memoria, cada nodo vuelve a calcular a
todos sus ancestros desde el conjunto completo: es el mismo defecto de Fibonacci ingenuo, pero
en un cálculo del YRBS. Con `functools.lru_cache`, cada segmento se calcula **una sola vez**.

Tres implementaciones del mismo resultado, en `F3/src/segmentacion.py`:

| Versión | Cómo trabaja | Costo esperado |
|---|---|---|
| recursiva ingenua | cada nodo filtra desde las 15.705 filas y repite a sus ancestros | O(nodos · n) |
| recursiva memoizada | cada nodo filtra solo el subconjunto (ya calculado) de su padre | O(profundidad · n) |
| `groupby` por nivel | una agrupación vectorizada por nivel y la poda aplicada después | O(profundidad · n) |

In [41]:
from segmentacion import ArbolPrevalencia, tabla_por_niveles_groupby

print(inspect.getsource(ArbolPrevalencia._subconjunto_sin_memoria))
print(inspect.getsource(ArbolPrevalencia.explorar))

    def _subconjunto_sin_memoria(self, filtros: tuple) -> np.ndarray:
        """Posiciones de los estudiantes del segmento definido por `filtros`.

        Caso base     : sin filtros, todos los estudiantes.
        Caso recursivo: el subconjunto del padre, filtrado por el último valor.
        """
        if not filtros:
            return self._todos
        padre = self._subconjunto(filtros[:-1])
        columna, valor = filtros[-1]
        self.llamadas_filtro += 1
        return padre[self._x[columna][padre] == valor]

    def explorar(self, filtros: tuple = ()) -> list:
        """Devuelve una fila por segmento visitado, en profundidad.

        Caso base     : se agotó la jerarquía o el segmento es menor que n_minimo.
        Caso recursivo: se desciende por cada valor observado de la variable
                        siguiente.
        """
        nivel = len(filtros)
        fila = {"nivel": nivel, "segmento": filtros, **self.estadisticas(filtros)}
        filas = [fila]
        if nivel == len(self.jerarquia) or fila["n"] < self.n_minimo:
            return filas                                   # caso base
        columna = self.jerarquia[nivel]
        posiciones = self._subconjunto(filtros)
        valores = np.unique(self._x[columna][posiciones])
        for valor in valores[~np.isnan(valores)]:
            filas += self.explorar(filtros + ((columna, float(valor)),))
        return filas

In [42]:
arbol = ArbolPrevalencia(datos, JERARQUIA_SEGMENTOS, "salud_mental_mala",
                         n_minimo=N_MINIMO_SEGMENTO, memoizar=True)
prevalencia_segmentos = arbol.tabla()
print(f"Segmentos visitados: {len(prevalencia_segmentos)} "
      f"(por nivel: {prevalencia_segmentos['nivel'].value_counts().sort_index().to_dict()})")
print(f"Estudiantes con el desenlace respondido: {arbol.estadisticas()['n']}\n")

# Nivel 2: uso de redes × sexo, en formato ancho para leerlo
nivel2 = prevalencia_segmentos[prevalencia_segmentos["nivel"] == 2].copy()
nivel2["redes"] = nivel2["segmento"].map(lambda s: int(s[0][1]))
nivel2["sexo"] = nivel2["segmento"].map(lambda s: {1: "femenino", 2: "masculino"}[int(s[1][1])])
tabla_redes_sexo = nivel2.pivot(index="redes", columns="sexo", values="pct")
tabla_redes_sexo.insert(0, "uso de redes", tabla_redes_sexo.index.map(proc.ETIQUETAS_REDES))
tabla_redes_sexo["diferencia_pp"] = (tabla_redes_sexo["femenino"] - tabla_redes_sexo["masculino"]).round(1)
print("% con salud mental no buena, por uso de redes y sexo (muestral, sin ponderar):")
tabla_redes_sexo

Segmentos visitados: 121 (por nivel: {0: 1, 1: 8, 2: 16, 3: 96})
Estudiantes con el desenlace respondido: 15705

% con salud mental no buena, por uso de redes y sexo (muestral, sin ponderar):

sexo              uso de redes  femenino  masculino  diferencia_pp
redes
1                       No usa      27.3       16.3           11.0
2            Unas veces al mes      24.7       14.1           10.6
3          Una vez a la semana      21.2       21.7           -0.5
4       Unas veces a la semana      35.4       18.0           17.4
5               Una vez al día      34.7       18.4           16.3
6          Varias veces al día      40.4       19.5           20.9
7             Una vez por hora      46.1       21.4           24.7
8      Más de una vez por hora      45.8       22.5           23.3

**Qué agrega la segmentación.** El gradiente por uso de redes aparece **en ambos sexos**, pero
con pendientes muy distintas: en las estudiantes la proporción de salud mental no buena sube de
alrededor de 27 % (no usa) a cerca de 46 % (una o más veces por hora); en los estudiantes, de
alrededor de 16 % a 22 %. La brecha entre sexos crece con la frecuencia de uso. Este resultado es
descriptivo y muestral: no controla otras variables ni aplica el diseño muestral, que se incorpora
en la Fase 4; lo que muestra es qué cruces conviene modelar.

In [43]:
# 1) Antes de medir: las tres versiones deben entregar la MISMA tabla
ingenua = ArbolPrevalencia(datos, JERARQUIA_SEGMENTOS, "salud_mental_mala", N_MINIMO_SEGMENTO, memoizar=False)
memoizada = ArbolPrevalencia(datos, JERARQUIA_SEGMENTOS, "salud_mental_mala", N_MINIMO_SEGMENTO, memoizar=True)
t_ing, t_mem = ingenua.tabla(), memoizada.tabla()
t_gb = tabla_por_niveles_groupby(datos, JERARQUIA_SEGMENTOS, "salud_mental_mala", N_MINIMO_SEGMENTO)
pd.testing.assert_frame_equal(t_ing, t_mem)
pd.testing.assert_frame_equal(t_ing, t_gb, check_dtype=False)
print(f"Las tres versiones entregan la misma tabla: {len(t_ing)} segmentos.\n")

# 2) El trabajo repetido, contado: cuántas veces se filtró un arreglo
print(f"Filtros aplicados, versión ingenua  : {ingenua.llamadas_filtro}")
print(f"Filtros aplicados, versión memoizada: {memoizada.llamadas_filtro}")
print(f"Memoria de la caché (lru_cache)      : {memoizada.info_cache()}")

Las tres versiones entregan la misma tabla: 121 segmentos.

Filtros aplicados, versión ingenua  : 368
Filtros aplicados, versión memoizada: 120
Memoria de la caché (lru_cache)      : CacheInfo(hits=145, misses=121, maxsize=None, currsize=121)

In [44]:
# 3) Tiempo y memoria según la profundidad de la jerarquía (tamaño real, n = 15.705)
JERARQUIA_EXTENDIDA = JERARQUIA_SEGMENTOS + ["sueno_cod"]


def version_ingenua(jer):
    return ArbolPrevalencia(datos, jer, "salud_mental_mala", N_MINIMO_SEGMENTO, memoizar=False).explorar()


def version_memoizada(jer):
    return ArbolPrevalencia(datos, jer, "salud_mental_mala", N_MINIMO_SEGMENTO, memoizar=True).explorar()


def version_groupby(jer):
    return tabla_por_niveles_groupby(datos, jer, "salud_mental_mala", N_MINIMO_SEGMENTO)


filas_memo = []
for profundidad in range(1, len(JERARQUIA_EXTENDIDA) + 1):
    jer = JERARQUIA_EXTENDIDA[:profundidad]
    a_ing = ArbolPrevalencia(datos, jer, "salud_mental_mala", N_MINIMO_SEGMENTO, memoizar=False)
    a_mem = ArbolPrevalencia(datos, jer, "salud_mental_mala", N_MINIMO_SEGMENTO, memoizar=True)
    segmentos = len(a_ing.explorar()); a_mem.explorar()
    fila = {"niveles": profundidad, "segmentos": segmentos,
            "filtros_ingenua": a_ing.llamadas_filtro, "filtros_memoizada": a_mem.llamadas_filtro}
    for nombre, funcion in (("ingenua", version_ingenua), ("memoizada", version_memoizada),
                            ("groupby", version_groupby)):
        fila[f"{nombre}_ms"] = round(min(timeit.repeat(lambda: funcion(jer), number=1, repeat=9)) * 1000, 2)
        fila[f"{nombre}_mb"] = round(medir(funcion, jer)[2], 3)
    filas_memo.append(fila)

eficiencia_memoizacion = pd.DataFrame(filas_memo)
eficiencia_memoizacion["ingenua / memoizada"] = (
    eficiencia_memoizacion["ingenua_ms"] / eficiencia_memoizacion["memoizada_ms"]).round(1)
eficiencia_memoizacion

,niveles,segmentos,filtros_ingenua,filtros_memoizada,ingenua_ms,ingenua_mb,memoizada_ms,memoizada_mb,groupby_ms,groupby_mb,ingenua / memoizada
0,1,9,8,8,2.87,4.483,3.17,4.483,8.16,11.424,0.9
1,2,25,48,24,5.26,4.604,5.57,4.604,13.59,11.424,0.9
2,3,121,368,120,14.90,4.724,7.51,4.724,18.66,11.424,2.0
3,4,530,2187,529,54.77,4.844,12.11,4.844,30.87,11.424,4.5

In [45]:
# Resumen de la medición en el caso más profundo
ultima = eficiencia_memoizacion.iloc[-1]
tamanos = ArbolPrevalencia(datos, JERARQUIA_EXTENDIDA, "salud_mental_mala", N_MINIMO_SEGMENTO).tabla()["n"]
cache_mb = tamanos.sum() * np.dtype("int64").itemsize / 1024 / 1024   # la caché guarda un arreglo por segmento
print(f"Con {int(ultima['niveles'])} niveles ({int(ultima['segmentos'])} segmentos):")
print(f"  ingenua  : {ultima['ingenua_ms']:.2f} ms, {int(ultima['filtros_ingenua'])} filtros")
print(f"  memoizada: {ultima['memoizada_ms']:.2f} ms, {int(ultima['filtros_memoizada'])} filtros "
      f"-> {ultima['ingenua / memoizada']:.1f} veces más rápida")
print(f"  groupby  : {ultima['groupby_ms']:.2f} ms -> {ultima['groupby_ms'] / ultima['memoizada_ms']:.1f} "
      f"veces el tiempo de la memoizada")
print(f"Memoria que retiene la caché: {cache_mb:.2f} MB (posiciones int64 de cada segmento)")

Con 4 niveles (530 segmentos):
  ingenua  : 54.77 ms, 2187 filtros
  memoizada: 12.11 ms, 529 filtros -> 4.5 veces más rápida
  groupby  : 30.87 ms -> 2.5 veces el tiempo de la memoizada
Memoria que retiene la caché: 0.47 MB (posiciones int64 de cada segmento)

**Interpretación.**

1. **El trabajo repetido crece con la profundidad.** Con un nivel no hay ancestros que repetir:
   ambas recursiones aplican los mismos 8 filtros y la memoizada es apenas más lenta por el costo
   de administrar la caché. Desde dos niveles la ingenua repite el trabajo de los ancestros en cada
   nodo: sus filtros crecen como *nodos × profundidad*, mientras la memoizada aplica exactamente un
   filtro por segmento (filtros = segmentos − 1). Con dos niveles el ahorro (24 filtros) todavía no
   compensa el costo de la caché y ambas quedan prácticamente empatadas; desde tres niveles la razón
   de tiempo crece con cada nivel, igual que en Fibonacci, pero ahora sobre un cálculo del proyecto.
2. **La memoizada también supera al `groupby`.** Aunque `groupby` es vectorizado, agrupa de nuevo
   las 15.705 filas en cada nivel y luego descarta los segmentos podados; la recursión memoizada
   solo trabaja dentro de los segmentos que sobreviven a la poda, y cada hijo filtra un arreglo cada
   vez más pequeño. `groupby` además tiene el mayor pico de memoria, por las tablas intermedias.
3. **Costo espacial.** La memoización cambia espacio por tiempo: la caché retiene las posiciones de
   cada segmento, O(profundidad · n) enteros, que en el tamaño real es del orden de 0,5 MB. El pico
   medido con `tracemalloc` no cambia entre ingenua y memoizada porque lo domina la preparación de
   los arreglos (≈4,5 MB), no la caché.

**Decisión.** Para la descripción por segmentos se adopta **la recursión memoizada**
(`ArbolPrevalencia(memoizar=True)`): entrega la misma tabla que las otras dos, es la más rápida
desde tres niveles, que es la profundidad de `JERARQUIA_SEGMENTOS`, admite la poda por tamaño mínimo sin calcular segmentos que luego se descartan
y su costo de memoria es menor a un megabyte. Este caso reemplaza al ejemplo de Fibonacci de la
Formativa 3.

---
# 15. Ejercicio 4 · Validación del pipeline real y del núcleo en tres escenarios

Se prueba el código del proyecto (no las clases didácticas) en:

- **Caso normal:** el archivo completo del CDC.
- **Casos límite:** situaciones extremas pero válidas (una fila, un estudiante sin ninguna respuesta, una sola categoría, un segmento más chico que el mínimo).
- **Excepciones:** entradas que deben detener el proceso con un mensaje claro.

In [46]:
# --- CASO NORMAL: el archivo completo ---
salida = proyecto
seleccion_ref = seleccion   # las 11 columnas antes de transformar

assert len(salida) == len(original) == 20103, "El pipeline perdió o duplicó filas"
print("[OK] Filas conservadas:", len(salida))

nulos_antes = seleccion_ref[VARIABLES_ANALISIS].isna().sum()
nulos_despues = salida[VARIABLES_ANALISIS].isna().sum()
assert (nulos_antes == nulos_despues).all(), "Cambiaron los faltantes: se imputó algo"
print("[OK] Faltantes idénticos antes y después en las 7 variables:", int(nulos_despues.sum()))

for columna in ["id_registro", "peso_muestral", "estrato", "psu"]:
    assert salida[columna].equals(seleccion_ref[columna]), f"{columna} fue modificada"
print("[OK] Identificador y diseño muestral intactos")

columnas_raza = list(RAZA.values())
con_dato = salida["raceeth_cod"].notna()
assert (salida.loc[con_dato, columnas_raza].sum(axis=1) == 1).all()
assert salida.loc[~con_dato, columnas_raza].isna().all().all()
print(f"[OK] Raza/etnicidad: suma 1 en {int(con_dato.sum())} filas y <NA> en {int((~con_dato).sum())}")

assert (salida["caso_completo"] == (salida["n_faltantes_analisis"] == 0)).all()
print("[OK] Bandera coherente:", int(salida["caso_completo"].sum()), "casos completos")

[OK] Filas conservadas: 20103
[OK] Faltantes idénticos antes y después en las 7 variables: 13813
[OK] Identificador y diseño muestral intactos
[OK] Raza/etnicidad: suma 1 en 19733 filas y <NA> en 370
[OK] Bandera coherente: 10941 casos completos

In [47]:
# --- CASOS LÍMITE ---

def correr(df):
    """Arma un pipeline nuevo y lo ejecuta sobre df (cada prueba parte de cero)."""
    return construir_pipeline_proyecto().ajustar(df).transformar(df)


# 1) Un conjunto de una sola fila funciona igual que el completo
r1 = correr(original.head(1))
assert r1.shape == (1, 26)
print("Límite 1: una sola fila ->", r1.shape)

# 2) Un estudiante que no respondió ninguna de las 7 preguntas
vacio = original.head(3).copy()
vacio.loc[vacio.index[0], proc.COLUMNAS_SIN_DEPENDENCIA] = np.nan
r2 = correr(vacio)
fila = r2.iloc[0]
assert fila["n_faltantes_analisis"] == 7 and fila["caso_completo"] == 0
assert r2.loc[r2.index[0], columnas_raza].isna().all()
assert r2.loc[r2.index[0], [n for _, _, n in INDICADORES]].isna().all()
print("Límite 2: sin ninguna respuesta -> 7 faltantes, caso incompleto, indicadores <NA> (no 0)")

# 3) Una sola categoría de raza: igual se crean las 8 columnas declaradas
blancos = original[original["raceeth"] == 5].head(50)
r3 = correr(blancos)
assert all(c in r3.columns for c in columnas_raza)
assert r3["raza_blanca"].eq(1).all() and r3["raza_negra"].eq(0).all()
print("Límite 3: una sola categoría -> 8 columnas, raza_blanca = 1 en todas")

# 4) Estrategia intercambiada: con moda ya no quedan faltantes, sin tocar otros pasos
r4 = construir_pipeline_proyecto(RellenarModa()).ajustar(original.head(500)).transformar(original.head(500))
assert r4[VARIABLES_ANALISIS].isna().sum().sum() == 0
print("Límite 4: cambiar la estrategia solo cambia el tratamiento de faltantes")

Límite 1: una sola fila -> (1, 26)
Límite 2: sin ninguna respuesta -> 7 faltantes, caso incompleto, indicadores <NA> (no 0)
Límite 3: una sola categoría -> 8 columnas, raza_blanca = 1 en todas

Límite 4: cambiar la estrategia solo cambia el tratamiento de faltantes

In [48]:
# --- EXCEPCIONES: entradas que deben fallar con un mensaje claro ---

def con_cambio(columna, fila, valor):
    """Copia pequeña del original con un valor alterado."""
    df = original.head(20).copy()
    df[columna] = df[columna].astype("object") if isinstance(valor, str) else df[columna]
    df.loc[df.index[fila], columna] = valor
    return df


pruebas = [
    ("código de raza fuera del codebook (9)", lambda: correr(con_cambio("raceeth", 0, 9)), ValueError),
    ("código no entero (q84 = 2.5)",          lambda: correr(con_cambio("q84", 0, 2.5)), ValueError),
    ("orig_rec con un dato",                  lambda: correr(con_cambio("orig_rec", 0, 1)), ValueError),
    ("archivo sin la columna q85",            lambda: correr(original.head(20).drop(columns=["q85"])), KeyError),
    ("record repetido",                       lambda: correr(con_cambio("record", 1, original["record"].iloc[0])), ValueError),
    ("transformar sin ajustar",               lambda: construir_pipeline_proyecto().transformar(original), RuntimeError),
    ("indicador sin valores positivos",       lambda: IndicadorBinario("sueno_cod", [], "x"), ValueError),
]

resultados = []
for descripcion, accion, esperada in pruebas:
    try:
        accion()
        resultados.append({"prueba": descripcion, "resultado": "NO lanzó excepción", "ok": False})
    except esperada as error:
        resultados.append({"prueba": descripcion, "resultado": f"{type(error).__name__}: {str(error)[:70]}", "ok": True})

tabla_excepciones = pd.DataFrame(resultados)
assert tabla_excepciones["ok"].all(), "Alguna excepción esperada no se lanzó"
tabla_excepciones

,prueba,resultado,ok
0,código de raza fuera del codebook (9),ValueError: CodificadorOneHot(raceeth_cod): có...,True
1,código no entero (q84 = 2.5),ValueError: CastearCodigos(códigos a Int64): '...,True
2,orig_rec con un dato,ValueError: EliminadorColumnaVacia(orig_rec): ...,True
3,archivo sin la columna q85,"KeyError: ""SeleccionadorColumnas(columnas de a...",True
4,record repetido,ValueError: SeleccionadorColumnas(columnas de ...,True
5,transformar sin ajustar,RuntimeError: Pipeline: hay que ajustar antes ...,True
6,indicador sin valores positivos,ValueError: valores_positivos no puede estar v...,True

In [49]:
# --- NÚCLEO ANALÍTICO (sección 14): límites y excepciones de ArbolPrevalencia ---

# Límite: si el mínimo supera al total, el árbol se detiene en la raíz (caso base inmediato)
solo_raiz = ArbolPrevalencia(datos, JERARQUIA_SEGMENTOS, "salud_mental_mala", n_minimo=10**6).tabla()
assert len(solo_raiz) == 1 and solo_raiz.loc[0, "nivel"] == 0
print("Límite: n_minimo mayor que el total -> solo la raíz")

# Límite: los faltantes de una variable de la jerarquía no forman un segmento propio
suma_hijos = prevalencia_segmentos.query("nivel == 1")["n"].sum()
con_redes = int(datos.dropna(subset=["salud_mental_mala", "redes_sociales_cod"]).shape[0])
assert suma_hijos == con_redes
print(f"Límite: los segmentos de nivel 1 suman {suma_hijos} = estudiantes con uso de redes respondido")

# Normal: el nivel 1 coincide con la tabla de contingencia de la sección 13 (dos caminos independientes)
nivel1 = prevalencia_segmentos.query("nivel == 1")["pct"].to_numpy()
assert np.allclose(nivel1, proporciones["porcentaje"].to_numpy())
print("Normal: el nivel 1 del árbol coincide con la tabla de contingencia (bincount)")

pruebas_nucleo = [
    ("columna inexistente en la jerarquía", lambda: ArbolPrevalencia(datos, ["no_existe"], "salud_mental_mala"), KeyError),
    ("n_minimo igual a cero", lambda: ArbolPrevalencia(datos, JERARQUIA_SEGMENTOS, "salud_mental_mala", n_minimo=0), ValueError),
    ("estrategia que no es EstrategiaFaltantes", lambda: TratamientoFaltantes(VARIABLES_ANALISIS, "moda"), TypeError),
    ("observador sin notificar()", lambda: PipelineObservable().suscribir(object()), TypeError),
    ("comparar versiones que no coinciden", lambda: comparar({"a": lambda: 1, "b": lambda: 2}), ValueError),
]
for descripcion, accion, esperada in pruebas_nucleo:
    try:
        accion()
        raise AssertionError(f"{descripcion}: no lanzó excepción")
    except esperada as error:
        print(f"  {descripcion:<42} {type(error).__name__}: {str(error)[:60]}")

Límite: n_minimo mayor que el total -> solo la raíz
Límite: los segmentos de nivel 1 suman 11602 = estudiantes con uso de redes respondido
Normal: el nivel 1 del árbol coincide con la tabla de contingencia (bincount)
  columna inexistente en la jerarquía        KeyError: "ArbolPrevalencia: no existen las columnas ['no_existe']."
  n_minimo igual a cero                      ValueError: n_minimo debe ser al menos 1.
  estrategia que no es EstrategiaFaltantes   TypeError: La estrategia debe heredar de EstrategiaFaltantes.
  observador sin notificar()                 TypeError: El observador debe tener un método notificar().
  comparar versiones que no coinciden        ValueError: 'b' no devuelve el mismo resultado que 'a'. No es una optimi

---
# 16. Ejercicio 5 · Strategy y verificación contra la Fase 2

## Por qué Strategy

- **Qué problema resolvía.** En la Fase 2 comparamos cuatro formas de tratar los faltantes y cada una era un bloque de código distinto; cambiar de decisión obligaba a reescribir el pipeline.
- **Cómo lo resuelve el patrón.** `TratamientoFaltantes` sabe *cuándo* tratar los faltantes y delega *cómo* hacerlo en una estrategia intercambiable (`ConservarFaltantes`, `RellenarModa`, `RellenarMediana`), que se elige al construir el pipeline.
- **Qué habría pasado sin él.** Probar otra estrategia (por ejemplo, si en la Fase 4 se decide imputar) habría significado editar el pipeline y arriesgar romper los demás pasos; ahora es cambiar un argumento.

La celda siguiente repite la comparación de la Fase 2, pero ahora **cambiando solo la estrategia**.

In [50]:
# Distribución de salud mental observada (solo quienes respondieron): la referencia
referencia = seleccion[COLUMNA_OBJETIVO].value_counts(normalize=True).sort_index() * 100

filas_estrategia = []
for estrategia in (ConservarFaltantes(), RellenarModa(), RellenarMediana()):
    salida_e = construir_pipeline_proyecto(estrategia).ajustar(original).transformar(original)
    serie = salida_e[COLUMNA_OBJETIVO].astype("float")
    distribucion = serie.value_counts(normalize=True).sort_index() * 100
    filas_estrategia.append({
        "estrategia": estrategia.etiqueta,
        "respuestas_usadas": int(serie.notna().sum()),
        "respuestas_inventadas": int(serie.notna().sum() - seleccion[COLUMNA_OBJETIVO].notna().sum()),
        "max_desvio_pp": round(float((distribucion - referencia).abs().max()), 1),
    })

pd.DataFrame(filas_estrategia)

     estrategia  respuestas_usadas  respuestas_inventadas  max_desvio_pp
0  conservar NA              15705                      0            0.0
1          moda              20103                   4398           15.3
2       mediana              20103                   4398           15.3

**Cómo se lee.** `max_desvio_pp` mide cuánto se aleja la distribución de salud mental de la que
realmente se observó. Rellenar con la moda o la mediana **inventa** miles de respuestas y las
concentra en una sola categoría, que se infla en varios puntos porcentuales. Por eso el proyecto
mantiene `ConservarFaltantes` (bitácora 2.5): es la única estrategia que no altera lo observado.

## La verificación que más rinde: ¿el pipeline de clases produce lo mismo que la Fase 2?

Se escribe la salida del pipeline de clases en formato CSV (en memoria, sin tocar el disco) y se
compara con el archivo que guardó la Fase 2, de dos formas:

1. `pd.testing.assert_frame_equal`: mismas columnas, mismo orden, mismos tipos y mismos valores.
2. Comparación del texto completo del archivo: debe ser **idéntico carácter por carácter**.

In [51]:
# Salida del pipeline de clases, escrita como CSV en memoria.
# lineterminator="\n": en Windows pandas termina las líneas con \r\n, pero al leer
# el archivo en modo texto Python las convierte a \n. Así ambos textos se comparan igual.
buffer = io.StringIO()
proyecto.to_csv(buffer, index=False, lineterminator="\n")
texto_f3 = buffer.getvalue()
nuevo = pd.read_csv(io.StringIO(texto_f3))

# Archivo guardado por la Fase 2
anterior = pd.read_csv(RUTA_DATOS)

# 1) Misma tabla
pd.testing.assert_frame_equal(anterior, nuevo)
print("assert_frame_equal: las dos tablas son iguales",
      f"({anterior.shape[0]} filas x {anterior.shape[1]} columnas)")

# 2) Mismo archivo, carácter por carácter
with open(RUTA_DATOS, encoding="utf-8") as archivo:
    texto_f2 = archivo.read()
identico = texto_f2 == texto_f3
print("Archivo idéntico carácter por carácter:", identico)
assert identico, "El CSV del pipeline de clases difiere del de la Fase 2"

print("\nLa reorganización en clases no alteró ni un valor del resultado de la Fase 2.")

assert_frame_equal: las dos tablas son iguales (20103 filas x 26 columnas)
Archivo idéntico carácter por carácter: True

La reorganización en clases no alteró ni un valor del resultado de la Fase 2.

---
# 17. El resultado: cómo queda el código y qué se registra

## 17.1 El código, antes y después

**Antes (Fase 2).** El pipeline era una secuencia de celdas que llamaban funciones sueltas; el
orden estaba implícito en la posición de las celdas:

```python
df = proc.cargar_datos(RUTA_RAW)
df = df.drop(columns=["orig_rec"])
df_sel = proc.seleccionar_columnas(df)
df_sel["n_faltantes_analisis"] = df_sel[columnas_analisis].isna().sum(axis=1)
df_t = castear_codigos(df_sel, columnas_analisis)
df_t = proc.transformar_datos(df_t)
df_t = codificar_one_hot(df_t, "raceeth_cod", RAZA)
for columna, positivos, nombre in INDICADORES:
    df_t = crear_indicador(df_t, columna, positivos, nombre)
```

**Después (Fase 3).** El mismo trabajo, con el orden declarado en un solo lugar:

```python
pipeline = construir_pipeline_proyecto(estrategia=ConservarFaltantes())
resultado = pipeline.ajustar(original).transformar(original)
```

El resultado es el mismo (sección 16). Lo que cambió es que ahora cada paso es una pieza con
nombre, que se puede probar, reemplazar y reutilizar sin tocar las demás.

## 17.2 La arquitectura, generada desde el propio código

En vez de escribir a mano la tabla de arquitectura, se produce leyendo las clases que existen y
**el archivo en que realmente está definida cada una** (`inspect.getfile`). Así no queda
desactualizada: si una clase se mueve de archivo, la tabla lo refleja en la siguiente ejecución.

In [52]:
from transformadores import CLASES_PROYECTO, CLASES_DIDACTICAS


def ubicacion(objeto):
    """Archivo donde está definido el objeto; 'cuaderno' si se definió aquí."""
    if objeto.__module__ == "__main__":          # definido en una celda de este cuaderno
        return "cuaderno"
    return Path(inspect.getfile(objeto)).relative_to(RAIZ).as_posix()


def primera_linea(objeto):
    return (objeto.__doc__ or "sin documentar").strip().splitlines()[0]


def documentar_arquitectura():
    """Genera la tabla de arquitectura a partir de las clases y funciones que existen.

    __subclasses__() devuelve las clases que heredan de una clase: es la misma
    información que Python usa para resolver la herencia.
    """
    componentes = [(Transformador, "clase base")]
    componentes += [(c, "clase hija (pipeline del proyecto)" if c in CLASES_PROYECTO
                     else "clase hija (didáctica)") for c in Transformador.__subclasses__()]
    componentes += [(c, "estrategia (Strategy)") for c in EstrategiaFaltantes.__subclasses__()]
    componentes += [(EstrategiaImputacion, "estrategia base (didáctica)")]
    componentes += [(c, "estrategia (didáctica)") for c in EstrategiaImputacion.__subclasses__()]
    componentes += [(leer_archivo, "entrada"), (verificar_esquema, "entrada"), (cargar, "entrada"),
                    (Pipeline, "orquestador"), (PipelineObservable, "orquestador (Observer)"),
                    (construir_pipeline_proyecto, "fábrica (Factory)"),
                    (crear_transformador, "fábrica (didáctica)"),
                    (Bitacora, "observador"), (ReporteConsola, "observador"),
                    (ArbolPrevalencia, "núcleo analítico (recursión + memoización)"),
                    (tabla_por_niveles_groupby, "núcleo analítico (alternativa vectorizada)"),
                    (AnalisisContingencia, "núcleo analítico (Formativa 3)"),
                    (medir, "utilidad de medición"), (comparar, "utilidad de medición")]
    componentes += [(c, "ejemplo (didáctico)") for _, c in inspect.getmembers(didacticos, inspect.isclass)
                    if c.__module__ == didacticos.__name__]
    tabla = pd.DataFrame([{"componente": o.__name__, "rol": rol, "responsabilidad": primera_linea(o),
                           "archivo": ubicacion(o)} for o, rol in componentes])
    tabla["uso"] = np.where(tabla["rol"].str.contains("didáctic"), "didáctico", "proyecto")
    return tabla


arquitectura = documentar_arquitectura()

# Ninguna clase se define en el cuaderno: todas se importan de F3/src/
clases_en_cuaderno = [n for n, o in list(globals().items())
                      if inspect.isclass(o) and o.__module__ == "__main__"]
assert not clases_en_cuaderno, f"Clases definidas en el cuaderno: {clases_en_cuaderno}"
assert (arquitectura["archivo"] != "cuaderno").all()
print(f"Clases definidas en el cuaderno: {len(clases_en_cuaderno)}. "
      f"Componentes documentados: {len(arquitectura)}, todos en archivos del repositorio.\n")

print("Componentes por archivo:")
print(arquitectura.groupby(["uso", "archivo"]).size().to_string(), "\n")
arquitectura[arquitectura["uso"] == "proyecto"].drop(columns="uso")

Clases definidas en el cuaderno: 0. Componentes documentados: 40, todos en archivos del repositorio.

Componentes por archivo:
uso        archivo
didáctico  F3/src/didacticos.py         5
           F3/src/estrategias.py        4
           F3/src/fabrica.py            1
           F3/src/transformadores.py    5
proyecto   F3/src/analisis.py           1
           F3/src/carga.py              3
           F3/src/estrategias.py        3
           F3/src/fabrica.py            1
           F3/src/medicion.py           2
           F3/src/observadores.py       2
           F3/src/pipeline.py           2
           F3/src/segmentacion.py       2
           F3/src/transformadores.py    9

,componente,rol,responsabilidad,archivo
0,Transformador,clase base,Clase base: define el contrato y controla el e...,F3/src/transformadores.py
1,EliminadorColumnaVacia,clase hija (pipeline del proyecto),Elimina una columna solo si está 100 % vacía (...,F3/src/transformadores.py
2,SeleccionadorColumnas,clase hija (pipeline del proyecto),Selecciona y renombra las columnas de análisis...,F3/src/transformadores.py
3,MarcadorFaltantes,clase hija (pipeline del proyecto),Agrega la bandera de faltantes: cuántas variab...,F3/src/transformadores.py
4,TratamientoFaltantes,clase hija (pipeline del proyecto),No sabe tratar faltantes: sabe cuándo hacerlo....,F3/src/transformadores.py
5,CastearCodigos,clase hija (pipeline del proyecto),"Convierte códigos float64 a entero Int64, cons...",F3/src/transformadores.py
6,ConversorOrdinal,clase hija (pipeline del proyecto),Declara el orden de las escalas ordinales con ...,F3/src/transformadores.py
7,CodificadorOneHot,clase hija (pipeline del proyecto),Codifica una nominal en columnas 0/1 con nombr...,F3/src/transformadores.py
8,IndicadorBinario,clase hija (pipeline del proyecto),Crea una columna 0/1 que vale 1 si el código e...,F3/src/transformadores.py
14,ConservarFaltantes,estrategia (Strategy),Estrategia del proyecto (bitácora 2.5): los fa...,F3/src/estrategias.py
15,RellenarModa,estrategia (Strategy),Alternativa evaluada en F2: rellenar con la ca...,F3/src/estrategias.py
16,RellenarMediana,estrategia (Strategy),Alternativa evaluada en F2: rellenar con la me...,F3/src/estrategias.py
21,leer_archivo,entrada,Lee el archivo según su extensión y devuelve u...,F3/src/carga.py
22,verificar_esquema,entrada,Comprueba que estén todas las columnas declara...,F3/src/carga.py
23,cargar,entrada,Carga el conjunto desde el archivo externo y v...,F3/src/carga.py
24,Pipeline,orquestador,Encadena transformadores y los ejecuta en orden.,F3/src/pipeline.py
25,PipelineObservable,orquestador (Observer),Pipeline que además notifica cada paso a sus o...,F3/src/pipeline.py
26,construir_pipeline_proyecto,fábrica (Factory),Fábrica: arma el pipeline de la Fase 2 como un...,F3/src/fabrica.py
28,Bitacora,observador,Observador que acumula lo ocurrido en cada pas...,F3/src/observadores.py
29,ReporteConsola,observador,Observador que imprime cada paso mientras ocurre.,F3/src/observadores.py
30,ArbolPrevalencia,núcleo analítico (recursión + memoización),Recorre recursivamente una jerarquía de segmen...,F3/src/segmentacion.py
31,tabla_por_niveles_groupby,núcleo analítico (alternativa vectorizada),Mismo árbol con un groupby por nivel y la poda...,F3/src/segmentacion.py
32,AnalisisContingencia,núcleo analítico (Formativa 3),Encapsula el cruce de dos variables ordinales ...,F3/src/analisis.py
33,medir,utilidad de medición,"Ejecuta la función y devuelve resultado, segun...",F3/src/medicion.py
34,comparar,utilidad de medición,Mide varias implementaciones del mismo cálculo...,F3/src/medicion.py

## 17.3 La Tabla 8 de la Formativa 3, ejecutada

En la Formativa 3 proyectamos en qué archivo de `F3/src/` iría cada componente (Tabla 8 de ese
informe: «Componentes, responsabilidades y ubicación propuesta»). La celda siguiente compara esa
planificación con el archivo en que **realmente** está definido cada componente, leído con
`inspect.getfile`. Si algún componente quedara en el cuaderno o en otro archivo, la celda falla.

La función de la Tabla 8 se llamaba `construir_pipeline`; hoy es `construir_pipeline_proyecto`,
porque arma los 12 pasos reales de la Fase 2 y no el pipeline didáctico de la Formativa.

In [53]:
# Tabla 8 de la Formativa 3: capa, componentes y archivo proyectado
PLAN_TABLA_8 = [
    ("Entrada",       [leer_archivo, verificar_esquema, cargar],               "F3/src/carga.py"),
    ("Núcleo",        [Transformador],                                         "F3/src/transformadores.py"),
    ("Núcleo",        [ImputadorMediana, CodificadorNominal, EscaladorEstandar,
                       EliminadorColumnas, ImputadorFlexible],                 "F3/src/transformadores.py"),
    ("Orquestación",  [Pipeline, PipelineObservable],                          "F3/src/pipeline.py"),
    ("Orquestación",  [construir_pipeline_proyecto],                           "F3/src/fabrica.py"),
    ("Soporte",       [Bitacora, ReporteConsola],                              "F3/src/observadores.py"),
    ("Soporte",       [medir],                                                 "F3/src/medicion.py"),
]

tabla8_ejecutada = pd.DataFrame([
    {"capa": capa, "componente": objeto.__name__, "archivo_proyectado": archivo,
     "archivo_real": ubicacion(objeto)}
    for capa, objetos, archivo in PLAN_TABLA_8 for objeto in objetos
])
tabla8_ejecutada["cumple"] = tabla8_ejecutada["archivo_proyectado"] == tabla8_ejecutada["archivo_real"]
assert tabla8_ejecutada["cumple"].all(), "Algún componente no está donde lo proyectó la Tabla 8"
print(f"{int(tabla8_ejecutada['cumple'].sum())} de {len(tabla8_ejecutada)} componentes "
      "están en el archivo que proyectó la Tabla 8.\n")
tabla8_ejecutada

15 de 15 componentes están en el archivo que proyectó la Tabla 8.

,capa,componente,archivo_proyectado,archivo_real,cumple
0,Entrada,leer_archivo,F3/src/carga.py,F3/src/carga.py,True
1,Entrada,verificar_esquema,F3/src/carga.py,F3/src/carga.py,True
2,Entrada,cargar,F3/src/carga.py,F3/src/carga.py,True
3,Núcleo,Transformador,F3/src/transformadores.py,F3/src/transformadores.py,True
4,Núcleo,ImputadorMediana,F3/src/transformadores.py,F3/src/transformadores.py,True
5,Núcleo,CodificadorNominal,F3/src/transformadores.py,F3/src/transformadores.py,True
6,Núcleo,EscaladorEstandar,F3/src/transformadores.py,F3/src/transformadores.py,True
7,Núcleo,EliminadorColumnas,F3/src/transformadores.py,F3/src/transformadores.py,True
8,Núcleo,ImputadorFlexible,F3/src/transformadores.py,F3/src/transformadores.py,True
9,Orquestación,Pipeline,F3/src/pipeline.py,F3/src/pipeline.py,True
10,Orquestación,PipelineObservable,F3/src/pipeline.py,F3/src/pipeline.py,True
11,Orquestación,construir_pipeline_proyecto,F3/src/fabrica.py,F3/src/fabrica.py,True
12,Soporte,Bitacora,F3/src/observadores.py,F3/src/observadores.py,True
13,Soporte,ReporteConsola,F3/src/observadores.py,F3/src/observadores.py,True
14,Soporte,medir,F3/src/medicion.py,F3/src/medicion.py,True

**Por qué esta división.** Cada archivo de `F3/src/` tiene una sola responsabilidad: la entrada
(`carga.py`) no conoce el pipeline; los pasos (`transformadores.py`) cambian si cambia una decisión
de datos; la forma de encadenarlos (`pipeline.py`), solo si cambia la orquestación; qué pasos se
arman (`fabrica.py`), solo si cambia la configuración; quién registra la ejecución
(`observadores.py`) se puede cambiar sin tocar el pipeline; las estrategias (`estrategias.py`) son
la parte que el equipo prevé modificar en la Fase 4; y el núcleo analítico (`segmentacion.py`,
`contingencia.py`) consume la salida del pipeline sin conocer sus pasos. Las clases de ejemplo
quedan aparte (`didacticos.py` y `CLASES_DIDACTICAS`), para que no se confundan con el proyecto.

## 17.4 Registro de la ejecución

Se guardan en `F3/resultados/` los archivos que permiten auditar la ejecución sin volver a
correr el cuaderno. **No se guarda un nuevo conjunto de datos**: el de la Fase 2 sigue siendo el
oficial, y la sección 16 demostró que el pipeline de clases lo reproduce exactamente.

In [54]:
os.makedirs(CARPETA_RESULTADOS, exist_ok=True)

registro_parametros = pd.DataFrame([
    {"orden": i, "paso": p.nombre, "clase": type(p).__name__, "parametros": str(p.parametros)}
    for i, p in enumerate(pipeline_proyecto.pasos_ejecutados(), start=1)
])
prevalencia_guardar = prevalencia_segmentos.assign(
    segmento=prevalencia_segmentos["segmento"].map(
        lambda s: " > ".join(f"{c}={int(v)}" for c, v in s) or "total"))

archivos = {
    "parametros_pipeline_f3.csv": registro_parametros,
    "bitacora_ejecucion_f3.csv": bitacora_proyecto.a_dataframe()[["paso", "filas", "columnas", "segundos"]],
    "arquitectura_f3.csv": arquitectura,
    "tabla8_ejecutada_f3.csv": tabla8_ejecutada,
    "eficiencia_faltantes_f3.csv": comparacion_faltantes,
    "eficiencia_crecimiento_f3.csv": tabla_crecimiento,
    "eficiencia_contingencia_f3.csv": eficiencia_contingencia,
    "eficiencia_busqueda_f3.csv": eficiencia_busqueda,
    "eficiencia_memoizacion_f3.csv": eficiencia_memoizacion,
    "prevalencia_segmentos_f3.csv": prevalencia_guardar,
}
for nombre, tabla in archivos.items():
    tabla.to_csv(CARPETA_RESULTADOS / nombre, index=False)
    releido = pd.read_csv(CARPETA_RESULTADOS / nombre)          # verificación de ida y vuelta
    assert releido.shape == tabla.shape, f"{nombre} no se releyó igual"
    print(f"Guardado y releído: F3/resultados/{nombre}  ({len(tabla)} filas)")

Guardado y releído: F3/resultados/parametros_pipeline_f3.csv  (12 filas)
Guardado y releído: F3/resultados/bitacora_ejecucion_f3.csv  (12 filas)
Guardado y releído: F3/resultados/arquitectura_f3.csv  (40 filas)
Guardado y releído: F3/resultados/tabla8_ejecutada_f3.csv  (15 filas)
Guardado y releído: F3/resultados/eficiencia_faltantes_f3.csv  (3 filas)
Guardado y releído: F3/resultados/eficiencia_crecimiento_f3.csv  (4 filas)
Guardado y releído: F3/resultados/eficiencia_contingencia_f3.csv  (4 filas)
Guardado y releído: F3/resultados/eficiencia_busqueda_f3.csv  (3 filas)
Guardado y releído: F3/resultados/eficiencia_memoizacion_f3.csv  (4 filas)
Guardado y releído: F3/resultados/prevalencia_segmentos_f3.csv  (121 filas)

---
# Cierre

## Dónde está cada concepto en este cuaderno

| Concepto | Evidencia en el código del proyecto | Sección |
|---|---|---|
| **Programación estructurada** | Funciones con contrato (`cargar`, `perfilar`, `preparar_pares`, `comparar`) y validación antes de actuar | 0, 13 |
| **Modularidad** | Ninguna clase se define en el cuaderno; cada componente está en el archivo que proyectó la Tabla 8 de la Formativa 3 | 17 |
| **Encapsulamiento** | `_parametros` y `_ajustado` internos; `nombre`, `parametros` y `ajustado` de solo lectura; `_codigos()` y `_ejecutar_paso()` internos | 3, 4, 11 |
| **Herencia** | 8 clases del proyecto heredan de `Transformador`; `PipelineObservable` hereda de `Pipeline`; 3 estrategias heredan de `EstrategiaFaltantes` | 4, 10, 11 |
| **Polimorfismo** | `Pipeline` llama `ajustar`/`transformar` sin preguntar el tipo; `TratamientoFaltantes` llama `tratar()` sin saber la estrategia; `columnas_requeridas()` redefinido | 4, 11 |
| **Patrones** | Strategy (principal), Factory y Observer (apoyo) | 10, 11, 16 |
| **Recursividad** | `aplanar()` (metadatos), búsqueda binaria y `ArbolPrevalencia.explorar()` con poda | 8, 13, 14 |
| **Memoización** | `functools.lru_cache` sobre el subconjunto de cada segmento | 14 |
| **Eficiencia** | Faltantes (bucle, `apply`, vectorizado), contingencia (4 versiones), búsqueda (3), segmentos (3), con `timeit` y `tracemalloc` | 9, 12, 13, 14 |
| **Validación** | Casos normales, límite y excepciones del pipeline real y del núcleo | 7, 15 |
| **Verificación contra F2** | `assert_frame_equal` y archivo idéntico carácter por carácter | 16 |

## Decisiones que quedan registradas

1. El pipeline de la Fase 2 se reorganiza en clases, que viven en `F3/src/` en los archivos proyectados en la Tabla 8 de la Formativa 3, sin cambiar su resultado.
2. Los faltantes se conservan (estrategia `ConservarFaltantes`), ahora como decisión explícita dentro del código.
3. El conteo de faltantes se hace de forma vectorizada: `apply` resultó la opción más lenta.
4. La tabla de contingencia usa `bincount` y la búsqueda por identificador, un diccionario.
5. La recursión se usa solo donde la profundidad es desconocida; donde además repite trabajo, se memoiza.

## Bibliografía (APA 7)

Gamma, E., Helm, R., Johnson, R., & Vlissides, J. (1994). *Design patterns: Elements of
reusable object-oriented software*. Addison-Wesley.

McKinney, W. (2022). *Python for data analysis* (3.ª ed.). O'Reilly Media.

Python Software Foundation. (s. f.). *functools — Higher-order functions and operations on
callable objects*. https://docs.python.org/3/library/functools.html

Python Software Foundation. (s. f.). *inspect — Inspect live objects*.
https://docs.python.org/3/library/inspect.html

Python Software Foundation. (s. f.). *timeit — Measure execution time of small code
snippets*. https://docs.python.org/3/library/timeit.html

The pandas development team. (s. f.). *pandas documentation*. https://pandas.pydata.org/docs/

Universidad Andrés Bello. (2026). *MCDI500 Programación para la Ciencia de Datos: Apunte Fase 3*
[Material docente]. Magíster en Ciencia de Datos e Inteligencia Artificial.

---

*Avance Fase 3 · Semana 2 · Sumativa 2 · MCDI500 · Grupo 8 · Magíster en Ciencia de Datos e
Inteligencia Artificial · Universidad Andrés Bello*